### ISSUE TITLE
ARIMA-style feed analysis: for {BoxCox=T/F, diff=0,1,2}, plot the seasonality and ACF/PACF

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#1009]
## Background / motivation

Parent epic: [#1006](https://github.com/oceanprotocol/pdr-backend/issues/1006) "Explore SARIMAX modeling"

**Top-level goal: Help user answer which of which transform to use {0, B0, B1, B2}, to (a) achieve stationarity; and (b) see how well the signal can decompose into trend / seasonal / residual.** 

**Specific transforms:**
  - 0: differencing = 0
  - B0: Box-Cox transform + differencing=0
  - B1: Box-Cox transform + differencing=1
  - B2: Box-Cox transform + differencing=1

**Sub-goals: We want it easy to see these:**
- decomposition into trend / seasonal / residual
- relative strengths of trend vs seasonality vs resid
- ACF & PACF. That is, autocorrelation function & partial autocorrelation function, for insight into best AR coefficient etc
- ADF for each transform {0, B0, B1, B2}. Insight: the lowest # that has ADF < 0.05 is the best
- Then, make it easy for the user to select a transform and see the plots ^ for that given transform

**Best ref:** jahnvisikligar Master's thesis https://github.com/jahnvisikligar/Masters-Thesis/blob/main/Final_Thesis_code.ipynb

## TODOs / DoD

- [x] Add real crypto data, ready for use by unit tests [PR #1016](https://github.com/oceanprotocol/pdr-backend/pull/1016)
- [ ] Unit test with plots for each sub-component:
  - [x] decomposition into trend / seasonal / residual [PR #1016](https://github.com/oceanprotocol/pdr-backend/pull/1016)
  - [x] relative strengths of trend vs seasonality vs resid [PR #1025](https://github.com/oceanprotocol/pdr-backend/pull/1025)
  - [x] ACF & PACF [PR #1026](https://github.com/oceanprotocol/pdr-backend/pull/1026)
  - [x] ADF for each transform {0, B0, B1, B2}. (Calc'd it as part of above line. Plots are being done in another issue).

## Main prototype: with everything

For a given choice of differencing {0,B0,B1,B2}, show
- 5 decomposition plots: energy per signal, plus 4 signals: (i) observed feed (ii) "trend" (iii) "seasonal", "residual".
- autocorrelation (ACF) & partial autocorrelation (PACF) plots

![Scan 11  May 2024, 10 55 page 2](https://github.com/oceanprotocol/pdr-backend/assets/5305452/5d0f8951-499b-4258-b40d-c2360f96f8ee)

### Prototype: decomposition into trend / seasonality / residual

![329284278-d9bbecce-9f5f-415f-be6e-c8da6d5d04b5](https://github.com/oceanprotocol/pdr-backend/assets/5305452/e959baaf-e150-4fd0-8989-720a2b627724)

### Prototype: For differencing=0,B0,B1,B2, show 5 decomposition plots
![Scan 11  May 2024, 10 55 page 1](https://github.com/oceanprotocol/pdr-backend/assets/5305452/29875489-5c43-4d29-bd3f-bc7376b3f488)

### Prototype:  For differencing=0,B0,B1,B2, show ACF & PACF

![1011](https://github.com/oceanprotocol/pdr-backend/assets/5305452/12aab994-9bf5-401f-af37-d64675927bd7)

### Example 0: neptune.ai "select model"

Ref: [neptune.ai select-model post](https://neptune.ai/blog/select-model-for-time-series-prediction-task)

```python
from statsmodels.tsa.seasonal import seasonal_decompose
result = seasonal_decompose(co2_data)
result.plot()
```
![example0](https://github.com/oceanprotocol/pdr-backend/assets/5305452/0abb3600-dff9-4979-a432-e4eac81752a7)

### Example 1a: Sikligar thesis, Differencing=0

Ref: [Sikligar thesis & code](https://github.com/jahnvisikligar/Masters-Thesis/blob/main/Final_Thesis_code.ipynb)

![example1a-differencing0](https://github.com/oceanprotocol/pdr-backend/assets/5305452/dde43790-bead-4d41-8da0-66ae26550c39)

### Example 1b: Sikligar thesis, Differencing=1

Ref: [Sikligar thesis & code](https://github.com/jahnvisikligar/Masters-Thesis/blob/main/Final_Thesis_code.ipynb)

![example1b-differencing1](https://github.com/oceanprotocol/pdr-backend/assets/5305452/99092e68-3823-41ac-8387-9ae33232c481)

### Example 2: neptune.ai catfish sales

```python
result = seasonal_decompose(lim_catfish_sales,model='additive')
fig = result.plot()
```

Ref: [neptune.ai catfish](https://i0.wp.com/neptune.ai/wp-content/uploads/2022/10/Arima-sarima-catfish-sales-4.png?ssl=1), in [this neptune.ai post/py code](https://neptune.ai/blog/arima-sarima-real-world-time-series-forecasting-guide).

![example2](https://github.com/oceanprotocol/pdr-backend/assets/5305452/d0c0569f-5477-4c9d-9217-caf73bccf44c)

**Comment by trentmc** [comment]
Seasonal decomposition of BTC/USDT close price Feb 1, 2024 - Mar 8, 2024

![Screenshot 2024-05-10 at 11 22 22](https://github.com/oceanprotocol/pdr-backend/assets/5305452/8b0701f2-e20e-4f52-b966-aa21e2d0138e)

**Comment by trentmc** [comment]
Part 1 done here: https://github.com/oceanprotocol/pdr-backend/pull/1016
