### ISSUE TITLE
[Sim plots] ARIMA plots of prediction residuals

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#1010]
Long-form title: Analyze model prediction sanity, via ARIMA-style diagnostic plots of prediction residuals

## TODOs

- [x] Create a unit test for this. Analyze via unit tests on real crypto data.
- [x] Put into sim_engine plotting
- [x] Fix DRY violations pointed out by Calina in PR
- [x] Ensure that plot is only shown for regressors, and not shown for classifiers
- [x] Create github issue for SHOW_PLOT=True moved to envvar. Here: [#1211](https://github.com/oceanprotocol/pdr-backend/issues/1211)

## Background / motivation

Parent epic: [#1006](https://github.com/oceanprotocol/pdr-backend/issues/1006) "Explore SARIMAX modeling"

Once we've built a model, we analyze the distribution of its residuals = (test data predicted value - test data actual value). There are four complementary diagnostics: raw residuals, histogram, QQ, ACF (correlogram). 

How: use one of:
  - `ARIMA_model.plot_diagnostics()` ([example](https://towardsdatascience.com/time-series-forecasting-with-arima-sarima-and-sarimax-ee61099e78f6)). 
  - `statsmodels.graphics.tsaplots.plot_acf`, `plot_pacf`, and ?? for QQ?  [Example 0: neptune.ai](https://neptune.ai/blog/select-model-for-time-series-prediction-task)
  - [NIXTLA StatsForecast library](https://nixtlaverse.nixtla.io/statsforecast/index.html)

## Prototype

![1010](https://github.com/oceanprotocol/pdr-backend/assets/5305452/7bfb6515-8919-4b24-b66c-9ffc0fb73937)

### Example 1: Sikligar thesis

[Ref - py notebook](https://github.com/jahnvisikligar/Masters-Thesis/blob/main/Final_Thesis_code.ipynb)

![Screenshot 2024-05-09 at 11 21 13](https://github.com/oceanprotocol/pdr-backend/assets/5305452/12399ac6-b113-456b-9bf6-896771c2b4e8)

### Example 2: PSU

[Ref - PSU course, lesson 03](https://online.stat.psu.edu/onlinecourses/sites/stat510)
![graph_30](https://github.com/oceanprotocol/pdr-backend/assets/5305452/e2b96b9f-495f-41b9-9818-8b16643ab673)

### Example 3: plot at different autocorrelation lags

Eg at lags of 1m, 2m, ..., 5m, 10m, ... 

[Ref ethan rosenthal.com](https://www.ethanrosenthal.com/2018/03/22/time-series-for-scikit-learn-people-part2/) 3 plots above "Reversible Transformations" section

![Screenshot 2024-05-09 at 11 23 10](https://github.com/oceanprotocol/pdr-backend/assets/5305452/f6487f5c-e9e9-4e72-96c2-4999e928500c)

Via this code

```python
import statsmodels.tsa.api as smt

def plot_multi_acf(data, lags, titles, ylim=None, partial=False):
    num_plots = len(lags)
    fig, ax = plt.subplots(len(lags), 1, figsize=(10, 3 * num_plots));
    if num_plots == 1:
        ax = [ax]
    acf_func = smt.graphics.plot_pacf if partial else smt.graphics.plot_acf
    for idx, (lag, title) in enumerate(zip(lags, titles)):
        fig = acf_func(data, lags=lag, ax=ax[idx], title=title);
        if ylim is not None:
            ax[idx].set_ylim(ylim);

    fig.tight_layout();

period_minutes = 5
samples_per_hour = int(60 / period_minutes)
samples_per_day = int(24 * samples_per_hour)
samples_per_week = int(7 * samples_per_day)

lags = [3 * samples_per_hour, samples_per_day, samples_per_week]
titles= ['Autocorrelation: 3-Hour Lag',
         'Autocorrelation: 1-Day Lag',
         'Autocorrelation: 1-Week Lag']

plot_multi_acf(y, lags, titles)
```
