### ISSUE TITLE
[Lake][Stats][App] Test app endpoint and document README.md for how to deploy/test it

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-backend#1048]
### Background / motivation

As a result of deploying duckdb, the `accuracy/app` has been updated to query from the lake.

This means that at some point, we'll have to redeploy the app and we need to:

### TODOs / DoD
1. make sure the app endpoint is working as expected
2. the app needs to have a lake, that it's constantly updating the tables + etl
3. have instructions for how to deploy this
4. have instructions for how to test that it's working
5. make sure the predictoor.ai FE still works once the new server is deployed

Tasks:
- [ ] make sure the app endpoint is working as expected
- [ ] the app needs to have a lake, that it's constantly updating the tables + etl
- [ ] have instructions for how to deploy this
- [ ] have instructions for how to test that it's working
- [ ] make sure the predictoor.ai FE still works once the new server is deployed

**Comment by kdetry** [comment]
We do not need ETL, only raw tables are enough for the accuracy module

**Comment by idiom-bytes** [comment]
Tracking outstanding items (including this) in [#1299](https://github.com/oceanprotocol/pdr-backend/issues/1299) and closing this to cleanup the backlog, until we have it resolved.
