### ISSUE TITLE
[DuckDB][Lake] Expand validation tool - Duplicate rows

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-backend#1058]
### Background / motivation

As part of completing the duckdb + #1000 epic and continuing to aim for high-data quality, we should likely have a better way to validate issues in the lake. Here are some recommendations I made:
- Updating `lake validate` to report duplicate rows on tables
- Updating `lake describe` to: report st_ts, end_ts, also in datestr format (st_ts_datestr, end_ts_datestr)
- Updating `lake describe` to provide a single summary across all tables so we can eventually put it on a dashboard (rather than outputting 12x different results that are hard to stitch together)
- Updating "lake validate gappiness" to work on other raw tables (slots and truevals)

### TODOs / DoD

Expand validation tool such that it tests for duplicate rows, and provides a report about duplicate rows/validations.

Tasks:
- [ ] Write duplicate row queries
- [ ] Aggregate results so we can write a report
- [ ] Generate a report based on tables & output
- [ ] Write duplicate validation errors & messages
- [ ] Write tests showing this validation is working as intended
- [ ] User is able to easily get a duplicate report at the lake level, across all tables
- [ ] User is able to easily get a report at the row level, across all tables

### Related github issues
https://github.com/oceanprotocol/pdr-backend/issues/618
https://github.com/oceanprotocol/pdr-backend/issues/1000
