### ISSUE TITLE
[DuckDB][ETL] Scope down Queries/ETL + Increase base quality

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-backend#1076]
**Describe the bug**
Like I had proposed before... we're still having issues in our queries/ETL that are causing a bunch of distractions. These are queries that extend beyond our core focus and we can increase in complexity after the basics are working well (example: slots).
![image](https://github.com/oceanprotocol/pdr-backend/assets/69865342/fa155a6d-c5ce-48f2-a1ae-72518445a7e3)

Our release candidate only needs 4: predictions, truevals, payouts + bronze_predictions
![Screenshot from 2024-05-21 08-15-24](https://github.com/oceanprotocol/pdr-backend/assets/69865342/436947a1-af1a-4f8b-9b61-e5f23860c300)

Once our pipeline is working end-to-end reliably, then, increase in complexity and add those queries back in. As you can see from the image above, by reducing the problem we can see that our bronze table `min_datestr` is not behaving as expected.

Isolate our target, get the whole thing working correctly end-to-end, then expand.

### DoD
- Scope down queries
- Increase quality of ETL

### Tasks
- [x] Disable slots and subscriptions raw_queries
- [x] Disable bronze_slots table
- [x] Fix issues across all 4 tables such that they are working as expected, end-to-end

**Comment by idiom-bytes** [comment]
**[Fix ETL - Move Temp Table to Live + Drop Temp Tables]**
There were some bugs/bad assumptions with how the "Temp Table" logic works inside etl.py... I believe i have fixed that now, and updated the tests to match this.

**[Table Registry]**
Due to the new NamedTables, I believe we can get rid of the TableRegistry object.
