### ISSUE TITLE
[EPIC][Model/trade] Full Predictoor support for Binance Futures

### ISSUE THREAD

**Issue by trizin** [oceanprotocol/pdr-backend#1084]
## Context

Binance futures has the lower fees and most liquidity, making it the best choice for trading.

## DoD

Note: There are no Binance Futures feeds on Predictoor at the moment. So we need to do that first.

### TODOs

- [ ] **Simulator can support futures, and we're making $**
  - [x] Build simulator support on historical data ("histmock") for predicting & trading on Binance Futures feeds for 5m epochs. Includes: Ensure that trading models how futures are done, rather than naive buys & sells. Confer with Jaime.
  - [ ] Tune parameters for ^, until trading is profitable on at least one of the feeds. (Proceed to next steps ONLY when profitable!)
  - [ ] Build simulator support for live data but mock trades ("livemock"). Tune parameters until trading is profitable. (Proceed to next steps ONLY when profitable!)
  - [ ] Build simulator support for live data and real trades ("livereal"). Tune parameters until trading is profitable. (Proceed to next steps ONLY when profitable!)
  - [ ] Build simulator support for ^ for 1h epochs
- [ ] **20 Binance Futures feeds working Ocean Barge (10 x 5min, 10 x 1h)**
  - [ ] Deploy 20 Binance Futures feeds to Ocean Barge
  - [ ] Iterating against Barge, update predictoor bot to work on new feeds on testnet. It might be trivial.
  - [ ] Iterating against Barge, update trader bot to work on new feeds on testnet. Likely a new trading approach, mimicking what was done in sim. Put another way: "trader bot should open, close long and short positions based on signals." Work may include a refactor of trader_agent.py or its sub-approaches (there's a lot of cruft right now.) 
- [ ] **20 Binance Futures feeds working on Sapphire testnet**
  - [ ] Deploy 20 Binance Futures feeds to Sapphire testnet. 
  - [ ] Ensure that address.json in `contracts/` repo is updated accordingly
  - [ ] Ensure that predictoor bot and trader bot work on new feeds on Sapphire testnet
- [ ] **20 Binance Futures feeds working on Sapphire mainnet**
  - [ ] Deploy 20 Binance Futures feeds to Sapphire testnet. 
  - [ ] Ensure that address.json in `contracts/` repo is updated accordingly
  - [ ] Ensure that predictoor bot and trader bot work on new feeds on Sapphire testnet
- [ ] Create follow-up github issues
  - [ ] Data Farming incentives on the new feeds?
  - [ ] Write blog post & tweet
  - [ ] Experiments? Other?

**Comment by trentmc** [comment]
Priorities have mostly shifted away from pdr-backend. So closing less-critical issues.
