### ISSUE TITLE
[DuckDB][First Candidate][Ratchet Up] Identify merge phases, and ratchet up the integration.

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-backend#1109]
### Background / motivation

After speaking with @trentmc about a merging strategy, rather than merging everything, ratchet up the integration. What is the order of components/updates we need, to cherry-pick/ratchet `duckdb-pr` -> into -> `main`

So, rater than doing funny things with the accuracy module... https://github.com/oceanprotocol/pdr-backend/pull/1057

Let;s make sure everything is running as best-as-possible, such that it's easy to merge from `duckdb-pr`to `main` in clean stes.

### TODOs / DoD
- [x] Identify steps to ratchet up duckb-integration into main
- [x] Begin small, by untangling dependencies, such that you can change some small parts
- [x] Start ratcheting up by replacing larger components and rles

### Related github issues
https://github.com/oceanprotocol/pdr-backend/pull/758
https://github.com/oceanprotocol/pdr-backend/pull/1057

**Comment by idiom-bytes** [comment]
Everything has been merged, closing issue
