### ISSUE TITLE
[Aimodel] Add simple SARIMAX aimodels, test, iterate

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#1118]
### Background / motivation

Parent epic: [#1006](https://github.com/oceanprotocol/pdr-backend/issues/1006) "Explore SARIMAX modeling"

SARIMAX models are promising. In this issue we implement and test simple versions. 

### Pre-requisite

[#1117](https://github.com/oceanprotocol/pdr-backend/issues/1117) "[Aimodel] Classifier-via-regressor"

### TODOs
- [ ] Choose a SARIMAX implementation: `NIXTLA` vs `pmdarima`. How: play with NIXTLA more. Details are in [#1006](https://github.com/oceanprotocol/pdr-backend/issues/1006)
- [ ] Add a simple SARIMAX model as >=1 aimodel approaches (as regressors)
- [ ] Test in sim_engine

**Comment by trentmc** [comment]
Closing this. Why: https://github.com/oceanprotocol/pdr-backend/issues/1006#issuecomment-2169137069
