### ISSUE TITLE
[Aimodel] Enable linear logistic classifier to use lasso, ridge, or elastic net

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#1133]
### Background / motivation

Our initial models were: LinearLogistic, LinearLogistic_Balanced, LinearSVC. All three are classifiers. The logistic models learn under a "ridge regression" cost function.

Then [#1117](https://github.com/oceanprotocol/pdr-backend/issues/1117) adds initial classifier-via-regressors: RegrLinearLS, RegrLinearLasso, RegrLinearRidge, RegrLinearElasticNet. And [#1118](https://github.com/oceanprotocol/pdr-backend/issues/1118) and [#1119](https://github.com/oceanprotocol/pdr-backend/issues/1119) add simple and fancy SARIMAX modeling.

To round things out: we want the optionality in how the linear logistic regrespsion classifiers get their weights learned, beyond just ridge regression). That is, to also support lasso and elastic net. While we're at it, we should make the naming more consistent with the classifiers.

### TODOs

- [x] Rename LinearLogistic -> ClassifLinearRidge, LinearLogistic_Balanced -> ClassifLinearRidge_Balanced
- [x] Rename LinearSVC -> ClassifLinearSVM (for consistency)
- [x] add ClassifLinearLasso and ClassifLinearLasso_Balanced
- [x] add ClassifLinearElasticNet and ClassifLinearElasticNet_Balanced

### Appendix : Alternative design (but don't use)

After this, it's 4 more models options.

Q: Is it better to allow variable arguments to be set in ppss, then pass them into LinearLogistic? 

The problem is, we can't easily sweep across those in multisim. 

Therefore, do _not_ do that. Maybe the future will need it, but not here.
