### ISSUE TITLE
[Sim_plots] 'model response' plots need to 'breathe' better: taller, and contour plots wider

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#1148]
### Background / motivation

Here's the current "model response" plots

![Screenshot 2024-06-07 at 13 29 44](https://github.com/oceanprotocol/pdr-backend/assets/5305452/4e9f258e-fe47-4e76-b047-3ed1ab73330d)

Problems:
- Bar plots are needlessly short. What if there are 20 vars? 
- And, bar plots are wider than needed. Whereas contour plots could happily be wider
- Contour plots are needlessly short. Ideally they are just as tall as they are wide, giving equal emphasis to the x0 dimension as the x1 dimension

### TODOs / DoD

- [ ] Make bar plot 2x-3x taller than status quo
- [ ] Make bar plot take 25%-35% of the width, and contour plot 65%-75% of the width
- [ ] Make contour plot height = its width (at least approximately)

**Comment by trentmc** [comment]
> Is this looking good?

Much, much better. Though the bar plot is not quite wide enough now.

See if you can reduce the whitespace between the two plots. 

And ideally the legend for the plot on the right isn't to the far right, but right above or below.

That might be enough to make the bar plot wide enough. If not, we can give it a slightly higher % of the width.

**Comment by trentmc** [comment]
Fixed in https://github.com/oceanprotocol/pdr-backend/commit/e9962cd1b51e47281f35692c951429388b307ab2
