### ISSUE TITLE
[ETL] Use revenue + roundStakes from `truevals` to update slots. Use revenue + roundStakes from `payouts` to calculate user-relative revenue.

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-backend#1183]
### Background / motivation

Previous ETL implementation has a bunch of artifacts that need to be moved around... After hooking up slots, remove revenue & roundSumStakes from payout.
- Previous implementation for payout, also retrieves slots data.
- revenue/roundSumStakes from slots data is stored in payouts table
- payouts table if anything, should calculate user-relative-revenue but does not

I made some adjustments here as a pseudo-implementation but will implement these later after update & slots is integrated.
![image](https://github.com/oceanprotocol/pdr-backend/assets/69865342/02406bd0-3c04-4b61-8b90-ba0ade9ea769)

### TODOs / DoD
After getting insert + updates in place, cleanup payout event and how user-relative-revenue is being calculated.

**Tasks:**
- [ ] Remove `revenue` and slots data from `payouts` table
- [ ] Calculate userRevenue inside payout (by using slots data) such that we have easy-to-access user-relative-revenue
- [ ] Revenues[] inside event `truevals.slot[]` also includes all user-relative revenue, but this would lead to a lot of joins
- [ ] Rather, we can optimize 1->N joins, by simply calculating user-relative revenue in the payouts event

**Comment by idiom-bytes** [comment]
This is now tracked with [#1299](https://github.com/oceanprotocol/pdr-backend/issues/1299), closing here and addressing this 1 by 1.
