### ISSUE TITLE
[Sim, Pdr bot] In sim and pdr bot tests, need to test both classifier _and_ regressor ai models

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#1208]
### Background / motivation

In sim engine tests: there's currently an end-to-end test for classifier. Same for sim plot and for pdr bot tests.

We recently added regression ai models. They're mostly the same to use as classifiers; but there are differences.

We've encountered at least one bug in pdr bot because it couldn't properly handle regression models.

Let's robust-ify our code.

### TODOs / DoD

- [ ] Pre-requisite: [#1209](https://github.com/oceanprotocol/pdr-backend/issues/1209) "Write basic end-to-end tests for sim plots & arima plots"
- [ ] In sim plot tests: ensure there's an end-to-end test for both classifier and regressor
- [ ] In sim engine tests: ""
- [ ] In pdr bot tests: ""

**Comment by trentmc** [comment]
Priorities have mostly shifted away from pdr-backend. So closing less-critical issues.
