### ISSUE TITLE
[Sim, Aimodel] Nudge regressor to have error -> 0 around current_price

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#1213]
### Background / motivation

We recently shipped regressors, wrapped by classifiers.

The regressors so far are global models (vs local ones that interpolate between points).

Therefore error on any given training point is typically >0. Including error around the current price.

But if there's non-negligible error at current price, then predictions near it will be pretty bad.

To address this, let's nudge the regressor to have error -> 0 around current_price.

Candidate ideas:
1. have 1000x weight on most recent sample, which forces it to have error --> 0.
2. add an offset to the model such that error on current price = 0. I could do this within each linear model's offset, or in a macro-way. Better to do it macro, because then it works for any regressor as we go beyond linear.

### TODOs / DoD

- [ ] Try idea (1), see how it goes
- [ ] Try idea (2), see how it goes
- [ ] Decide whether to keep none, one or both
