### ISSUE TITLE
[EPIC, Aimodel] ARIMA-inspired features + FFX

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#1220]
### TODOs

- [ ] Box-Cox transform on input
- [ ] Support diff=0 and diff=1 on all vars
- [ ] Support exponential moving average (EMA) on different # scales
- [ ] Support weekly & daily seasonal components : use Fourier terms sin() & cos() like in https://otexts.com/fpp2/weekly.html
- [ ] FFX regr
- [ ] FFX classif

### Related github issues

- [#1006](https://github.com/oceanprotocol/pdr-backend/issues/1006) [EPIC, aimodel, sim] Explore SARIMAX modeling

### Appendix

```
What I want:
- Box-Cox transform on input
- vastly more input variables, as follows:
  - for each of {BTC, ETH, ...} x {close, volume, volatility}
    - for each of {diff=0, diff=1}
      - AR components
      - EMA (exponential moving average) on different # scales
      - daily-seasonal components : use Fourier terms sin() & cos() like in https://otexts.com/fpp2/weekly.html
      - weekly-seasonal components
- A modeling technique that can easily handle
  - a large # input variables
  - simple interactions among the variables
  - naturally smooth (vs piecewise-constant)
  - top of my list: FFX for regression, and for classification

### Autoregressive
Have one input variable for each of x[t-1], x[t-2], ..., x[t-autoregressive_n]
AR - autoregressive_ns = [1, 2, 3, 5, 10, 50, 100, 200, 288]

### Moving Average Smoothed
have one input variable for each mas_n. MAS = moving average
*smoothing*
 - mas_ns = [3, 5, 10, 25, 50, 100, 200, 288]

### One model would have these x-vars

- diff=0
  AR
  - x[t-1]
  - x[t-2]
  - x[...]
  - x[t-autoregressive_n]

  MAS/EMA (MAS shown)
  - avg[x[t-1],x[t-2],x[t-3])
  - avg[x[t-1],x[t-2],...,x[t-5])
  - avg[x[t-1],x[t-2],...,x[t-10])
  - avg[x[t-1],x[t-2],...,x[t-25])
  - avg[x[t-1],x[t-2],...,x[t-50])
  - avg[x[t-1],x[t-2],...,x[t-100])
  - avg[x[t-1],x[t-2],...,x[t-200])
  - avg[x[t-1],x[t-2],...,x[t-288]) # number of 5-min epochs in 1 day

  Daily-seasonal components
  -

  Weekly-seasonal components
  -


- diff=1
  AR
  - x[t-1] - x[t-2]
  - x[t-2] - x[t-3]
  - x[t-3] - x[t-4]
  - x[...]
  - x[t-autoregressive_n] - x[t-4]

  MA
  - avg(x[t-1] - x[t-2], x[t-2] - x[t-3])
  - avg[x[t-1] - x[t-2], x[t-2] - x[t-3], x[t-3] - x[t-4])
  - avg[x[t-1] - x[t-2], x[t-2] - x[t-3], ..., x[t-5] - x[t-5-1])
  - avg[x[t-1] - x[t-2], x[t-2] - x[t-3], ..., x[t-10] - x[t-10-1])
  - avg[x[t-1] - x[t-2], x[t-2] - x[t-3], ..., x[t-25] - x[t-25-1])
  - avg[x[t-1] - x[t-2], x[t-2] - x[t-3], ..., x[t-50] - x[t-50-1])
  - avg[x[t-1] - x[t-2], x[t-2] - x[t-3], ..., x[t-100] - x[t-100-1])
  - avg[x[t-1] - x[t-2], x[t-2] - x[t-3], ..., x[t-200] - x[t-200-1])
  - avg[x[t-1] - x[t-2], x[t-2] - x[t-3], ..., x[t-288] - x[t-288-1])

  Daily-seasonal components
  -
 
  Weekly-seasonal components
  -
 
- diff=2
  (skip)
```
