### ISSUE TITLE
[Aimodel] Add xgboost & gaussian process models

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#1243]
### Background / motivation

So far we have only linear models. We've held back from nonlinear modeling until we're in better shape wrt data engineering.

We're now at the point to start adding some nonlinear models.

xgboost & gaussian processes are good starting points: they're well-understood, relatively straightforward to apply, and aren't too heavy computationally

To decide: for each, whether to support as classifier, or regressor, or both

### TODOs

- [x] add gaussian process regressor
- [x] add gaussian process classifier
- [ ] sim_plots aren't working on GPs when # train_n > 200. Solve it
- [ ] add xgboost
