### ISSUE TITLE
[Sim] Transform lake data into prediction signals for trader

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/pdr-backend#1263]
### Target

Create prediction signal that is suitable to be used for the trader step

Parent epic: [#1257](https://github.com/oceanprotocol/pdr-backend/issues/1257) Integrate subgraph prediction into sim trading

### TODO

- [x] Transform the lake data into prediction signals
Read data from pdr_payouts table, filter payouts by slot and calculate the prediction from `roundSumStakes` and `roundSumStakesUp`
Final data should be stored `slot - prediction` pairs list
- [x] Use prediction signal inside trader sim
- [x] Test and Verify
