### ISSUE TITLE
[Sub-EPIC] Add unit tests & refactor submodules

### ISSUE THREAD

**Issue by trizin** [oceanprotocol/pdr-backend#13]
[Part of epic [#50](https://github.com/oceanprotocol/pdr-backend/issues/50) "Ship MVP"]

### TODOs

Add unit tests & refactor submodules for each of:

- [x] utils
  - [x] [Trent] subgraph https://github.com/oceanprotocol/pdr-backend/commit/5b364d226cf56838d91c99a51299232c91e0492c
  - [x] [T] constants https://github.com/oceanprotocol/pdr-backend/commit/5b364d226cf56838d91c99a51299232c91e0492c
  - [x] [Berkay] contract.py - Berkay [PR](https://github.com/oceanprotocol/pdr-backend/pull/53) 
  - [x] [B,Calina] Berkay walk Calina through unit-testing setup, general onboard into pdr-backend
- [x] [C,T] predictoor
- [x] [C] trader
- [x] [B] trueval
- dfbuyer --> moved to [#128](https://github.com/oceanprotocol/pdr-backend/issues/128)
- publisher --> moved to [#129](https://github.com/oceanprotocol/pdr-backend/issues/129)

**Comment by trentmc** [comment]
This is all done except publisher and dfbuyer agents. They're less urgent. Therefore I've created a new github to test & refactor each of those; and we can schedule accordingly.

Therefore _this_ github issue is done!
