### ISSUE TITLE
[Epic][PdrDashboard] Analytics for predictoors

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#1328]
### Background / motivation

Our core users are predictoors & traders who use our pdr-backend python bots. We want to reduce friction for them. 

Even though they operate largely in python-land, there are things we can do in the webapp to help them out.

Top (or near top) of the list is to help them answer the Q: "How much $ am I making / losing". There are many drill-down Q's that emerge from that.

This epic is for predictoors. We will do a follow-on epic for traders, when appropriate.

### TODOs: Predictoor Dashboard

- [x] Explore top-level Q's, and drill-down Q's. Done: [this comment](https://github.com/oceanprotocol/pdr-backend/issues/1328#issuecomment-2203374184). And other comments too! :)  
- [x] Prototype visuals. Done: [here (Gslides)](https://docs.google.com/presentation/d/18y_nfpc3e-dop5NtfIisgUkc-oPt8dft9WyAnqhSqZg/edit#slide=id.g20f5357f625_0_1639)
- [ ] Build dashboard, iteratively
  - v0.1 [#1325](https://github.com/oceanprotocol/pdr-backend/issues/1325)
  - v0.2 [#1357](https://github.com/oceanprotocol/pdr-backend/issues/1357)
  - v0.3 [#1422](https://github.com/oceanprotocol/pdr-backend/issues/1422)
  - v0.4 [#1473](https://github.com/oceanprotocol/pdr-backend/issues/1473)
- [ ] (When appropriate) create similar epic for trader dashboard. Link to this one. 

### Related

- [pdr-web#48](https://github.com/oceanprotocol/pdr-private/issues/48) is "[Predictoor FE] Backlog". It has some analytics-related issues. _This_ issue needs to reconcile with that.
- [pdr-web#66](https://github.com/oceanprotocol/pdr-anl/issues/2) is "Predictoors Leaderboard". It's likely a subset of this, but useful to keep open for now because we'll almost certainly want to highlight the leaderboard; and we want to ensure that it doesn't get missed
- (closed - duplicate) [pdr-private#38](https://github.com/oceanprotocol/pdr-private/issues/38) is "Fetch, visualize and monitor prediction metrics". There was overlap between that issue and this one. So we closed pdr-private#38.

**Comment by trentmc** [comment]
Much of this has been built, over several iterations. Any future steps can be their own issue. 

AND: Priorities have mostly shifted away from pdr-backend. So closing less-critical issues.
