### ISSUE TITLE
[analytics, predictoor_v0.2] Improve basic predictoor dashboard

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/pdr-backend#1357]
**Target**
Improve the basic predictoor dashboard to use a predictoor first approach in order to make it easier to interact with the app and visualize predictoor data just by selecting a predictoor address.

Super epic issue can be found [here](https://github.com/oceanprotocol/pdr-backend/issues/1328)
UI should follow the layout from [here](https://docs.google.com/presentation/d/18y_nfpc3e-dop5NtfIisgUkc-oPt8dft9WyAnqhSqZg/edit#slide=id.g20f5357f625_0_1639)

To do:
- [ ] make stats more readable
- display accuracy, profit and avg stake as numbers at the top of the page for selected values ( helpful to see profit across many feeds and predictoors )

- [ ] improve tables
- add the following buttons: select all, clear all(clears all selected values) 

- [ ] improve predictoors table
- make user column values shorter
- add profit, accuracy and avg stake
- sort table by profit on default 

- [ ] make it easy to access predictoor specific stats over all feeds
- instead of selecting each feed for a given predictoor I just want to select or provide a predictoor address and see stats across all feeds. The feeds table could only contain feeds for which the selected predictoor has made predictions for and all feeds selected by default (enable and disable this is done by a toggle)

- [ ] data period actions
- allow user to select a specific period for the stats (24h, 1week, 1month, all), probably by some buttons or tabs
- display the range of data available in the lake by displaying first and last date
