### ISSUE TITLE
[PdrDashboard] v0.3: costs, tooltips and final improvements

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/pdr-backend#1422]
### Target

Add costs, tooltips and final fixes and updates to make the UX of the first page of dashboard better before moving to other pager

Super epic issue can be found [here](https://github.com/oceanprotocol/pdr-backend/issues/1328)

### TODO
- [x] rename the y-axis labels on each plot to: [1433](https://github.com/oceanprotocol/pdr-backend/issues/1433) - Norbert
   - accuracy(%), Profit(OCEAN), Stake(OCEAN)
- [x] accuracy plot rescale to min 30 - 70 bounds [1433](https://github.com/oceanprotocol/pdr-backend/issues/1433) - Norbert
   - the accuracies are mostly between this 2 values so updating the bound will eliminate the free spaces
- [x] show confidence interval if 1 track is shown [1434](https://github.com/oceanprotocol/pdr-backend/issues/1434) - Mustafa
   - similar to what we have inside the simulation plots, so confidence intervals inside the accuracy plot, but only of just 1 
      track is shown 
- [x] display selected table rows as first elements [1439](https://github.com/oceanprotocol/pdr-backend/issues/1434) - Calina
    - when fields are selected, especially on predictoors table with pre configured addresses, if they are not in between the 
       first x visible rows, it’s not clear that there are any rows selected. Once something is selected sort the rows so that is 
       displayed at the start
- [x] display gas fee costs [1438](https://github.com/oceanprotocol/pdr-backend/issues/1438) - Norbert
     - calculate the gas fees costs by looking at the cost of 1 prediction tx cost and multiply it by an avg gas price value
     - create a new costs plot and 'rename' the current plot to ‘stakes'
     - display total costs on top along side the other
- [x] add tooltips [1464](https://github.com/oceanprotocol/pdr-backend/issues/1464) - Mustafa
     - app starts to get more and more features and some of the metrics and inputs need more context and explanation
- [x] display number of rows from within each table [1441](https://github.com/oceanprotocol/pdr-backend/issues/1441) - Mustafa
     - next to table name, display number of rows so we know how many predictoors and feeds are in the system
- [x] bug: https://github.com/oceanprotocol/pdr-backend/issues/1447 If predictoor is selected the search on feeds is not working
- [x] bug: https://github.com/oceanprotocol/pdr-backend/issues/1453 Predictoor table columns from startup don't match with later renditions of the same table
- [x] bug: Plotly can not order properly the X axis on some cases [1462](https://github.com/oceanprotocol/pdr-backend/issues/1462) - Mustafa
 
### UI sketch for v0.3:
<img width="976" alt="Screenshot 2024-07-19 at 12 22 58" src="https://github.com/user-attachments/assets/30c9a23c-d0e2-4deb-aacb-6baad3891c17">
