### ISSUE TITLE
[EPIC] Full backend support for ten 60-minute feeds

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#144]
### Background / motivation

5-min feeds don't have enough price delta to make up for 0.1% fees. So it's hard to make $.

But 60-min feeds have 20x the volume, and therefore much greater potential to make $.

A key goal is to help our users make $ readily. Accordingly, we're promising that "for mainnet", we will have 60-min feeds.

Note: The ten feeds are BTC/USDT, ETH/USDT, ... . Do _not_ bother with BTC/TUSD (only have that in 5-min feeds).

### TODOs: 

- [x] Get 60-min flow working for local. Includes: publish >=one 60-min contracts in barge. Update agent code / tests / READMEs as needed (publisher, trueval, trader, predictoor 1, predictoor 2, dfbuyer)
- [ ] Get 60-min flow working for testnet
  - [x] Publish all 60min feeds to testnet
  - [ ] Ensure agents include 60min [pdr-backend#182](https://github.com/oceanprotocol/pdr-backend/issues/182)
- [ ] Get 60-min flow working for mainnet 
  - [x] Publish all ten 60-min feeds to mainnet [pdr-private#31](https://github.com/oceanprotocol/pdr-private/issues/31)
  - [ ] Run agents on mainnet, incl 60min [pdr-backend#183](https://github.com/oceanprotocol/pdr-backend/issues/183)

Note: FE issue for 60-min feeds is: [pdr-web#161](https://github.com/oceanprotocol/pdr-web/issues/161)

**Comment by idiom-bytes** [comment]
### Problem
I'm currently discussing the need for us (FE team) to maintain testing and building inside dev environment rather than relying on testnet. We just shipped 1hr contracts that broke that FE.

### Candidate Solutions
1. Perhaps we should add another publish() call inside `pdr-publisher.main.py` that deploy a `1h` interval contract?
1. Or perhaps a separate main/bootstrap that runs a "full bootstrap sim" that contains all requirements for the 60m release?

### Notes
- I believe we should be validating everything is working internally, in this "full bootstrap sim" logic sequence, so we can validate the stack + product (UI) is working e2e.

**Comment by trentmc** [comment]
This issue is partly complete.

All the remaining tasks have their own issue, and are tracked in the "MVP" epic [pdr-backend#50](https://github.com/oceanprotocol/pdr-backend/issues/50). 

Therefore we can close _this_ issue.
