### ISSUE TITLE
[Lake] Fix lake + etl to work w/ latest subgraph

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-backend#1457]
### Background / motivation
Issues w/ subgraph and data need to be reflected on lake/etl

### TODOs / DoD
- [x] get lake raw update working
- [x] get lake etl update working
- [x] validate everything is working and no duplicate rows are being generated
