### ISSUE TITLE
[trader] Check subscriptions at start and use asyncio to process blocks

### ISSUE THREAD

**Issue by trizin** [oceanprotocol/pdr-backend#146]
### Background
Currently _process_block_at_feed takes 0.8 seconds to run on average if the prediction is available, otherwise 0 seconds. So it takes around 8.8 seconds to process 11 feeds. In order to reduce the processing time:

### TODO
- [ ] Check subscriptions at start (and subscribe if doesn't exist)
- [ ] Use asyncio to process blocks.
- [ ] Regularly check subscription status.

**Comment by trentmc** [comment]
What's the problem that this issue is trying to solve? Please expand the description to say so.
