### ISSUE TITLE
[Lake Info] Update Overview and HTML to not break

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-backend#1460]
### Background / motivation
Issue 1 - Lake Info should use summary queries, samples, and other approaches to handle larger datasets. Such that it does not `select * all` from lake and still provides the user with the insights they need
(a) overview.py fetches all data from all tables and caches it in memory
(b) HTML uses a _filter() function that rather looking at cached data, it fetches again from db...
(c) issue (3) takes this further and fetches data many times rather than once, caching the result, and displaying it everywhere

![image](https://github.com/user-attachments/assets/d57d0923-65d0-4d86-b4c0-28e4cf2cba45)

Issue 2 - _filter_table is implemented in a "generic manner" but underlying logic `get_filtered_result` doesn't actually use what's cached in memory, and instead does another query to the DB w/ a filter selection only on `user` column...

![image](https://github.com/user-attachments/assets/f15dc923-213e-4210-a884-8592e2ba288f)
![image](https://github.com/user-attachments/assets/1b15df3b-67eb-4865-a96b-13ca355cbb13)

Issue 3 - html.py has to call `_filter_table` many times, causing multiple fetches/computes to be done rather than 1
![image](https://github.com/user-attachments/assets/2f44429a-baaa-49e6-8dbb-88ce9e6f0d95)
![image](https://github.com/user-attachments/assets/18119852-ed5c-4d90-9317-99db8c855ed9)

### TODOs / DoD
1. fix lake implementation to be more memory/compute aware...
- [ ] overview.py should not fetch all data from all tables from lake
- [ ] html/frontend->lake should implement basic practices of pagination, sampling, row_count, and performing basic summaries such that it's considerate of data size
2. get_filtered_result should be implemented propery
- [ ] `get_filered_result` should work as as expected
3. html.py calls `_filter_table` multiple tables to provide the same overview... this costs n-times the memory/computation/etc... rather than once
- [ ] `filter_table` should only be done once across the whole page... perhaps across the whole app by caching this information somewhere that it can be accessed

**Comment by trentmc** [comment]
Priorities have mostly shifted away from pdr-backend. So closing less-critical issues.
