### ISSUE TITLE
[PdrDashboard] v0.4: Feeds page

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/pdr-backend#1473]
### Target

Add a new page dedicated to feeds, where users can leverage a big table containing all the existing feeds with multiple metrics and properties.

Super epic issue can be found [here](https://github.com/oceanprotocol/pdr-backend/issues/1328)

### TODO
- [x] Add navigation and transform dapp into multipage application [#1474](https://github.com/oceanprotocol/pdr-backend/issues/1474) - Norbert
    - Add Home and Feeds navigations
    - Replace current dashboard title with navigation
    - When clicking on home redirect to current predictoor dashboard, on Feeds show the new Feeds page
- [x] #1485
    - Under the menu display a row containing main metrics over all feeds, such as: Volume, Feeds, Sales, Revenue, Accuracy(avg)
- [x] Create a table that contains all the columns from the mockup provided bellow  [#1478](https://github.com/oceanprotocol/pdr-backend/issues/1478) - Mustafa
- [x] Create a filters section that contains multiple components for different columns and allow table filtering [#1484](https://github.com/oceanprotocol/pdr-backend/issues/1484) - Norbert
    - The components should be compressed and the dropdown list should open when component is clicked
    - Add a Reset All button then clears all the filter values
- [ ] Add search bar that allow search based on: Add, Base Token, Quote token, Exchange [#1520](https://github.com/oceanprotocol/pdr-backend/issues/1520) - Norbert
- [x] Expandable rows [#1506](https://github.com/oceanprotocol/pdr-backend/issues/1506) - Calina / Norbert
    - when clicking on a specific row, the address should be saved and a component should open
    - when clicking again the component should close
- [x] Create and display data inside expanded row [#1506](https://github.com/oceanprotocol/pdr-backend/issues/1506)  - Norbert
    - display following charts: Volume, Sales, Accuracy, Predictions, Stakes over time
- [ ] Dash_duo / selenium tests for the new page
- [x] #1491 split up utils.py
- [x] create a yaml file for tooltip texts
- [x] Create and implement NumberFormatter [#1501](https://github.com/oceanprotocol/pdr-backend/issues/1501) - Mustafa
- [x] Find and add the websocket buyer address to the DF buyers, only for this module [#1508](https://github.com/oceanprotocol/pdr-backend/issues/1508) - Mustafa
- [x] Fix the table title and do nor remove the "Avg" phrase  [#1501](https://github.com/oceanprotocol/pdr-backend/issues/1501) - Mustafa
- [x] Fix the legend on the home page and remove the exchange name from the legend items [#1515](https://github.com/oceanprotocol/pdr-backend/issues/1515) - Mustafa

### UI sketch for v0.4:
- inspiration from [DefiLlama](https://defillama.com/yields)
<img width="1317" alt="Screenshot 2024-07-29 at 16 20 55" src="https://github.com/user-attachments/assets/0fefe225-402e-461a-beb6-04846f5f0866">

<img width="953" alt="Screenshot 2024-07-29 at 16 22 40" src="https://github.com/user-attachments/assets/6a93482d-439a-43ee-8db3-61d9b04c81d7">
