### ISSUE TITLE
[PdrDashboard, v0.4] Add navigation menu and a new Feeds page

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/pdr-backend#1474]
### Background / motivation

link to epic: [#1473](https://github.com/oceanprotocol/pdr-backend/issues/1473)

Create a new Feeds page, and add navigation menu to navigate between the 2 pages

### TODOs / DoD

- [x] Add Home and Feeds navigation menu items
- [x] Replace current dashboard title with navigation
- [x] When clicking on home redirect to current predictoor dashboard, on Feeds show the new Feeds page
