### ISSUE TITLE
[PdrDashboard] Post v0.5 improvements

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/pdr-backend#1559]
### TODOs / DoD

- [x] [#1560 - Norbert](https://github.com/oceanprotocol/pdr-backend/issues/1560) Improvements around the queries to have less and reuse data between pages.
   ex: use the same function to get all predictoors related data before the app starts in one place instead of using 1 method for home page predictoors table(payouts_stats) and Predictoors page table (predictoor_payouts_stats). The 2 table should have the same data source
- [x] [#1571 - Norbert](https://github.com/oceanprotocol/pdr-backend/issues/1571 ) Display available lake date period at the top of the page and allow date period selection by button click
- [x] [#1577 - Mustafa](https://github.com/oceanprotocol/pdr-backend/issues/1577) Switch from payouts to bronze_predictions which are incrementally updated
- [x] [#1572 - Mustafa](https://github.com/oceanprotocol/pdr-backend/issues/1572) Add more columns to home page feeds table: Avg Accuracy, Sales and fix column sorting for both tables from home page
- [x] [#1648 - Norbert](https://github.com/oceanprotocol/pdr-backend/issues/1648) Rename “Net income” to “Profit” because it can have negative values
- [x] Add  “Profit” metric to predictoors page
- [x] [#1645 - Norbert](https://github.com/oceanprotocol/pdr-backend/issues/1645) Tx costs on the home page look to be broken, it is the same value or very small variations between time periods(1D, 1W, 1M)
- [x] [#1648 - Norbert](https://github.com/oceanprotocol/pdr-backend/issues/1648) Feeds page modal, rename ‘Predictions’ -> ’Nr of Predictions’
- [ ] On Feds page Sales column explain what DF(data farming) and WS(web socket) sales mean. This could be done either by a tooltip, or inside the column header name etc
- [x] [#1648 - Norbert](https://github.com/oceanprotocol/pdr-backend/issues/1648) Display the data period end date time, so if there are multiple update withing a day we know at what time the last update occurred. We could also display how often we update the data( rn it happens hours, and an indicator for this is seconds_between_parquet_export from the ppss file) 
- [x] Upgrade dash testing. See dependencies.md for the full context. https://github.com/oceanprotocol/pdr-backend/pull/1647

**Comment by kdetry** [comment]
` Switch from payouts to bronze_predictions which are incrementally updated`

Do we need it? The current queries rely on the payouts and are well tested.

**Comment by KatunaNorbert** [comment]
> Do we need it? The current queries rely on the payouts and are well tested.

If we want to have more accurate/up to date data then yes.
Right now we relay on certain calculations only on payout data and that could be outdated(User has to claim), for example there were cases where people were only calling the payout for right predictions( on this case, we also have to also look to predictions and consider those where there was no payout as loss or wrong ).

**Comment by kdetry** [comment]
I am okay with this explanation, so I look at it

**Comment by trentmc** [comment]
Basically done
