### ISSUE TITLE
[Model/trade] Technical indicators support

### ISSUE THREAD

**Issue by trizin** [oceanprotocol/pdr-backend#1579]
## Background
The Python [ta](https://technical-analysis-library-in-python.readthedocs.io/en/latest/) library has 200+ "technical analysis" indicators. Taking these as inputs (along with their interactions, eg -, /, *) could be very useful. (from https://github.com/oceanprotocol/pdr-backend/issues/1406)

## TODOs

**Step1:** https://github.com/oceanprotocol/pdr-backend/pull/1578
- [x] Implement [ta](https://pypi.org/project/ta/) interfaces/classes into pdr-backend 
- [x] Update `predict_train_feedsets` to accept an array of technical indicators
- [x] Indicators are calculated & used as a feature in simengine

**Step2:**
- [ ] Create technical indicator string class to parse parameters
- [ ] More indicators
- [ ] Use pdr sim to assess performance compared to our status quo
- [ ] Try variants. Eg with different interactions, different ML models

**Step3:**
- [ ] Predictoor integration

**Comment by trentmc** [comment]
Priorities have mostly shifted away from pdr-backend. So closing less-critical issues.

**Comment by trentmc** [comment]
Priorities have mostly shifted away from pdr-backend. So closing less-critical issues.
