### ISSUE TITLE
[PdrDashboard] Loading UI improvements

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/pdr-backend#1627]
### Background / motivation

Improve UI for better data loading and display experience

### TODOs / DoD

- [ ] Add loading icons only for the data that's waited to be loaded, for the others display the component( ex: Navbar menu is displayed only when available lake data range is received from the backend )
- [ ] Add 1W for selected period to improve short term visibility and initial data loading
- [ ] Add margin to the app body to have some spacing between the content and the browser width&height
- [ ] If no predictoor addrs is configured, select one by default so when app loads, the chars on the home page are not empty
