### ISSUE TITLE
Implement DF for Oasis via new script that airdrops ROSE weekly

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#170]
### Background / motivation

Oasis will participate in Predictoor DF with ROSE tokens. A few thousand $ worth per week (specifics TBD).

Then the question is: how do we best support this?

A challenge: dfbuyer is buying feeds using OCEAN, not ROSE.

This was discussed [in slack](https://oceanprotocol.slack.com/archives/C051UV3J3T4/p1695293981308809). Best approach is below.

### TODO

- [ ] Write a new script that does a weekly ROSE airdrop to predictoors, pro-rata with how much they earned in the previous week
- [ ] Ensure script is well tested
- [ ] Include script as part of weekly DF ops (github actions)

**Comment by alexcos20** [comment]
>  Write a new script that does a weekly ROSE airdrop to predictoors, pro-rata with how much they earned in the previous week
That might not work, since earning can only be tracked if a predictoor claimed his rewards.   For gas purposes, some predictoor could claim once per day -> inaccurate results.

What about using:
 - even based on number of predictions (trackable real-time through subgraph)
 - based on amount of staked tokens (although this can lead to some gaming opportunities)

>  Include script as part of weekly DF ops (github actions)
Should we deploy df claims on sapphire and have df-py use a private key and actually generate the tx?
On mainnet, we are generating the tx on multisig, but there is no multisig on sapphire

**Comment by trentmc** [comment]
> What about using: ... based on .. # predictions .. [or] # staked tokens

Problems:
- these are gameable
- more complex mental model for Predictoors, because now they have two objective functions (the one for everything else, and the one for ROSE)

Better to stick with the same objective function as the rest, which seems like the most robust wrt being gamed. (And I'm sure it will have attacks, and we'll update it. But we do it once, for everything).

**Comment by trentmc** [comment]
> (Alex 3): Combine (Alex 1) and (Alex 2) : have a new smartcontract that can send ROSE to multiple addresses ( (or update DFRewards to handle native tokens) ) controlled with a private key that df-py has. -> only one txs needed from df-py
> I lean towards (Alex 3)

Agreed

**Comment by alexcos20** [comment]
> > What about using: ... based on .. # predictions .. [or] # staked tokens
> 
> Problems:
> 
> * these are gameable
> * more complex mental model for Predictoors, because now they have two objective functions (the one for everything else, and the one for ROSE)
> 
> Better to stick with the same objective function as the rest, which seems like the most robust wrt being gamed. (And I'm sure it will have attacks, and we'll update it. But we do it once, for everything).

How do we calculate earnings?  There is no way, unless predictor calls 'claim' and that gets recorded in our subgraph.  If he does not,  there is no way of calculate earnings.
So we make sure that all predictoors must call "claim" for the last rounds of each Wed night, in order to get rewards? And before df-py runs :)

**Comment by alexcos20** [comment]
> > (Alex 3): Combine (Alex 1) and (Alex 2) : have a new smartcontract that can send ROSE to multiple addresses ( (or update DFRewards to handle native tokens) ) controlled with a private key that df-py has. -> only one txs needed from df-py
> > I lean towards (Alex 3)
> 
> Agreed

https://github.com/oceanprotocol/contracts/issues/813

**Comment by alexcos20** [comment]
> > Must wait for predictoors to call "claim" ..
> 
> So perhaps we just do payouts pro-rata on the week that they claim?

Yeah, it's the most clean solution for now.

**Comment by trentmc** [comment]
Sounds good to me

**Comment by trentmc** [comment]
Closing because duplicate - see Berkay's comment right above this one

**Comment by trentmc** [comment]
Duplicate with https://github.com/oceanprotocol/df-py/issues/721
