### ISSUE TITLE
Support S2 EthMiami predictoor competition: write competitor README, judging code, etc

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#255]
### Rules

- **To be eligible, competitors must:**
  - Be running a local (or remote) predictoor bot on Sapphire testnet
  - Report their predictoor's address to the judges _before_ `time1`. (This is important, to avoid sybil attacks by competitors) 
  - Submit a prediction for every 5m slot in the interval starting at `time1` = FIXME and ending at `time2` = FIXME, for `feed` = ETH/USDT on Binance.
- **Criteria for winning**
  - Whoever had the highest % of correct predictions during the interval of `time1` to `time2` 
- **Benefit:** competitors have onboarded to become predictoors - and therefore towards doing sustainable work in the Ocean ecosystem

### TODOs by S3

- [ ] Create affordances for competitors
  - [ ] Write a competitor README, including (a) Rules above (b) a link to the pdr-backend READMEs to do the predictions
- [ ] Create affordances for judges 
  - [ ] Write code to be able to judge. Including at least:
    - For each competitor: calculate % of correct predictions during the interval of `time1` to `time2` 
    - Output eg a log or table where each row has competitor address and  % correct

**Comment by nickscavuzzo33** [comment]
@trentmc Thanks for this, next hurdle is what do you think about the asset we want them to predict? Options are 1) ETH 2) any other erc20 token ie OCEAN, LINK, UNI or 3) external commodity .... 3 would need a different data source than Binance API

**Comment by trentmc** [comment]
Q from Christian [in slack](https://oceanprotocol.slack.com/archives/C051UV3J3T4/p1697638280537209):

Having gone through the steps thus far, if the goal is to get the users having a local predictoor on remote network, it honestly seemed simpler to just give them a readme that goes straight there. It was kind of more confusing to first have it running locally with barge and random predictions and then working way up, since it felt like some work was duplicated. It felt like it would've been easier to just follow one path of instructions instead of jumping back and forth.
Other than trying to keep it simple for partipants, was there a paritclar reason why we couldn't have people follow one end-to-end instruction flow to get to local predictoor on remote network?

**Comment by ChristianCasazza** [comment]
The goal would be to have one single README to point to for participants in the competition to build their own model and begin submitting predictions using a local predictoor to a remote network, One potential way is to create a consolidated README using [localPredictoorRemoteNetwork]( https://github.com/oceanprotocol/pdr-backend/blob/98208390a38459662184dd48a69d4c89ad702d6e/READMEs/localbot-remotenet.md) as a base.

The information from [get tokens](https://github.com/oceanprotocol/pdr-backend/blob/98208390a38459662184dd48a69d4c89ad702d6e/READMEs/get-tokens.md) and [install PDR-backend](https://github.com/oceanprotocol/pdr-backend/blob/98208390a38459662184dd48a69d4c89ad702d6e/READMEs/install.md) are small and could be added directly into the README instead of linking away.

For the purposes of the competition, we could remove the references to the random predictions and trading and focus the README on going through Approach3:  Dynamic models.

The README could end as it does now, with running the PM2 bot

By consolidating all the information into one README, it may be a streamlined process for participants to quickly get set-up with their models and become onboarded as predictoors

**Comment by trentmc** [comment]
> would need a different data source than Binance API

In the issue description, I added the pre-requisite: "US would-be predictoors can't see binance data from ccxt or binance api" [pdr-private#37](https://github.com/oceanprotocol/pdr-private/issues/37) _OR_ publish a new feed on testnet that they can see, eg kraken

> what do you think about the asset we want them to predict? Options are 1) ETH 2) any other erc20 token ie OCEAN, LINK, UNI or 3) external commodity 

Ideally it's something that's already published as a prediction feed, and visible in predictoor.ai. It doesn't make sense to add work, we're all busy enough. The US issue is a constraint that we will have to solve though.

**Comment by trentmc** [comment]
> simpler to just give them a readme that goes straight [to local bot, remote network]

In the issue description, I added the pre-requisite: "Remove onboarding friction: README goes straight to local bot / remote network" [pdr-backend#258](https://github.com/oceanprotocol/pdr-backend/issues/258)

> create a consolidated README

Yes, this makes sense. Once the above is done, we can do this as part of this issue. I updated the description.

**Comment by nickscavuzzo33** [comment]
to get to approach 3 i have used portions from these 3 readmes to get started 

[1 ](https://github.com/oceanprotocol/pdr-backend/blob/98208390a38459662184dd48a69d4c89ad702d6e/READMEs/localpredictoor-localnet.md#install-local-network)
[2](https://github.com/oceanprotocol/pdr-backend/blob/98208390a38459662184dd48a69d4c89ad702d6e/READMEs/localbot-remotenet.md#get-tokens)
[3](https://github.com/ChristianCasazza/pdr-backend/blob/main/READMEs/dynamic-model.md#run-dynamic-model-predictoor)

total steps (on MacBook) and blocker for approach 3 [currently](https://docs.google.com/document/d/1Rji4W7G0gCadoo5lMAKMmjDZNuUI23Em0Wx8ViNyahk/edit#heading=h.d77nnlfrf85f)

**Comment by trentmc** [comment]
@nickscavuzzo33 , please hold off from doing this. It's a waste of time. I'm going to have to redo it anyway.

**Comment by trentmc** [comment]
Hi @trizin the EthMiami README is now done: https://github.com/oceanprotocol/pdr-backend/blob/main/READMEs/ethmiami.md

Therefore, as discussed, I've reassigned this issue to you, to handle the judging script. (Details in issue description.) Thanks again:)
