### ISSUE TITLE
[Sim] model for slippage, via openmesh.network data. Bonus: put into trader

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#274]
### Background / motivation

We've found that slippage makes a huge difference to profitability. Slippage can be thought of as extra fees.

For bot flow (pdr_backend/trader): fees and slippage are naturally modeled in trader bots, because they're trading on real world data in real time. We've observed this in practice.

For simulation flow (pdr_backend/predictoor/approach3): it already models fees. But it does _not_ model slippage.

_Jaime's_ simulations _do_ model slippage by bringing in historical + realtime orderbook data purchased from kaiko. By modeling it, and accurately, he was able to devise a trading strategy to account for it.
- But this is not yet part of the approach3 simulation flow
- And it uses data that opf had to purchase

In early Oct 2023, Trent met the founder of [openmesh.network](https://openmesh.network) (Ashton) who shared that they have historical + realtime orderbook data, for free. 
- A potential hitch: openmesh.network may not have everything we need. If this is the case, we can investigate other options. [See "Where & How to Get Crypto Data" GDoc.](https://docs.google.com/document/d/1IRjk01Siw0Ne4URnl2JVV27ul1VIz-eCX4rcGWb-8UM/edit#heading=h.yqyh7s2rqhmu). 
- A hitch: the non-ccxt API will be different than ccxt. So it'll take effort to change things
- Bonus: the non-ccxt may have Binance trading pairs available. If yes, this could be the cleanest solution to [pdr-private#37](https://github.com/oceanprotocol/pdr-private/issues/37) "US would-be predictoors can't see binance data from ccxt or binance api"

### TODOs

- [ ] Find free historical + realtime orderbook data. Starting point: play with openmesh.network
- [ ] Update simulation flow (and maybe more) with new data source for status quo data
- [ ] Update simulation flow to model slippage
- [ ] (Bonus) update simulation flow where trader accounts for slippage, using Jaime's heuristic
- [ ] (Bonus) update trader bot flow to account for slippage using the the heuristic ^

**Comment by trentmc** [comment]
Using a github issue isn't the place to track this. We are tracking in the "Make $" GDoc. Can close this, to reduce mental overhead
