### ISSUE TITLE
[EPIC] [Sim, bots] Easy sim --> pdr/trader bot flow w plots

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#278]
## Background / motivation

`pdr_backend` offers three flows for predictoors & traders:
- "simulation flow" - for rapid iterations to test predictoor approaches and trader approaches
- "predictoor bot flow" - put a predictoor approach live, make $
- "trader bot flow" - put a trader approach live, make $

Accordingly, predictoor.md and trader.md READMEs use the simulation flow.

The aim of this epic is to make the interaction of "simulation flow" to "bot flow" truly excellent.
- The big trick is "can easily port a predictoor/trader approach from simulation flow to predictoor/trader bot"
- But there are pre-requisites to that
- And once we have those, then we can optimize simulation more aggressively, with immediate payoff to predictoor and trader bots
- Then we can bring it into webapps

This epic organizes the work, so we do things in the appropriate order.

## TODOs

**Do first: (pre-requisites for others)**
- [x] [Trader bot] Add approach1 to do simplistic trading [#271](https://github.com/oceanprotocol/pdr-backend/issues/271)
- [x] [Simulation] Refactor: move simulation flow from "predictoor/approach3" to "simulation/" [#277](https://github.com/oceanprotocol/pdr-backend/issues/277)

**Then: fix bugs in simulation**
- [x] "ValueError: Input X contains NaN", so can't predict TRX/USDT [#266](https://github.com/oceanprotocol/pdr-backend/issues/266)
- [x] trade_engine.py KeyError: 'TRX' [#327](https://github.com/oceanprotocol/pdr-backend/issues/327)
- [x] Fix "WARNING: diffs not ok: mn=3600000, mx=3600000" [#263](https://github.com/oceanprotocol/pdr-backend/issues/263)
- [x] breaks on 1h epochs (probably) [#273](https://github.com/oceanprotocol/pdr-backend/issues/273)

**Plots: low-hanging fruit**
- [x] **Status quo plots.** In pdr_backend "simulation flow" (pdr_backend/predictoor/approach3), locally generate & show matplotlib plots at the end of the sim. Show profit vs. time for traders, predicted vs actual for predictoors, etc. We already have a first-cut of this, and will improve organically.
- [x] **Add realtime plots to sim.** In pdr_backend "simulation flow", locally generate & show matplotlib plots **in realtime** as the simulation progresses. [pdr-backend#279](https://github.com/oceanprotocol/pdr-backend/issues/279)
- [x] [Sim] Plot % correct vs time, with confidence intervals [#272](https://github.com/oceanprotocol/pdr-backend/issues/272)

**Better flow from sim -> bot; YAML; CLI**

The rest of this is being handled in "[EPIC: YAML] **Add YAML & CLI. 'v0.2' of Predictoor"** [#370](https://github.com/oceanprotocol/pdr-backend/issues/370). 

Therefore we can close _this_ issue.
