### ISSUE TITLE
get_predictoor_info.py needs to be more modular, and tested

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#296]
### Background / motivation

[get_predictoor_info.py](https://github.com/oceanprotocol/pdr-backend/blob/main/scripts/get_predictoor_info.py) was recently built for to help EthMiami judging. 

Example output, from [this slack thread](https://oceanprotocol.slack.com/archives/C054ZHZ11RU/p1698332084628139?thread_ts=1698332065.964699&cid=C054ZHZ11RU):
```text
Overall Accuracy: 51.08%
Accuracy for Pair: ADA/USDT, Timeframe: 5m: 50.63%
Total stake: 282.70319568418233
Total payout: 174.74360545310648

Accuracy for Pair: XRP/USDT, Timeframe: 1h: 50.00%
Total stake: 26.458942555410236
Total payout: 11.77390896354474

Accuracy for Pair: ETH/USDT, Timeframe: 5m: 52.08%
Total stake: 277.54203431195
Total payout: 149.30581199262107
...
```

This is a great start. It / its components can be useful in many places.

However it's not possible to re-use it elsewhere because its components are all within the script itself. 

And, it's not tested. It could have errors.

### Components

Each bullet below is a component in the script. 

- `class Prediction` 
- `get_all_predictions()` subgraph query
- `write_csv()` to output predictions to a csv 
- `date_to_unix()` 
- `get_statistics()` 

### TODOs

Here are recommended refactors. (They may be a bit different in practice, as it gets done. That's fine.)

- [ ] `class Prediction` --> put in `models/`, as its own module `prediction.py`. With unit tests.
- [ ] `get_all_predictions()` subgraph query --> put in `util/subgraph.py` or new file `util/subgraph-predictions.py`. Add unit test.
- [ ] deprecate `date_to_unix()`, use functions in predictoor/approach3/timeutil.py instead. (BTW the location of timeutil.py is not general enough; we have another github issue to handle that.)
- [ ] `write_csv()` --> put into new module `csvs.py`, call it `predictions.csv`. Unit test it. (Have it follow the same pattern as the csvs.py files in df-py, such as [volume/csvs.py](https://github.com/oceanprotocol/df-py/blob/main/df_py/volume/csvs.py))
- [ ] `get_statistics()` currently (a) retrieves data, (b) computes statistics, and (c) prints it. Move the function into a new module `util/predictoor_stats.py`. Refactor the function into two functions: (a)(b) together, and (c) separate. Unit test each function.
- [ ] Have `get_predictoor_info.py` use the above modules in each of their locations. (And now, they're all tested, and reusable FTW)
