### ISSUE TITLE
get_rpc_url_or_exit() is messy, delete it. And similar

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#35]
### Status quo ("Cand 1")

`pdr_backend/dfbuyer/main.py` currently has
```python
rpc_url = env.get_rpc_url_or_exit()
subgraph_url = env.get_subgraph_or_exit()
private_key = env.get_private_key_or_exit()
pair_filters = env.get_pair_filter()
timeframe_filter = env.get_timeframe_filter()
source_filter = env.get_source_filter()
owner_addresses = env.get_owner_addresses()
```

It's similar for siblings of dfbuyer: pdr-trader, publisher, etc.

Where `get_rpc_url_or_exit()`  etc are implemented in pdr_backend/utils/env.py:
```
def get_rpc_url_or_exit() -> str:
    return get_envvar_or_exit("RPC_URL")

def get_subgraph_or_exit() -> str:
    return get_envvar_or_exit("SUBGRAPH_URL")

def get_private_key_or_exit() -> str:
    return get_envvar_or_exit("PRIVATE_KEY")

def get_pair_filter() -> str:
    return get_envvar("PAIR_FILTER")

def get_timeframe_filter() -> str:
    return get_envvar("TIMEFRAME_FILTER")

def get_source_filter() -> str:
    return get_envvar("SOURCE_FILTER")

def get_owner_addresses() -> str:
    return get_envvar("OWNER_ADDRS")
```

### Problems with status quo

This has two problems:

- That's a *lot* of code just for envvar management. 
- It's an extra layer of indirection, which adds complexity and hurts understandability
- It obfuscates to the developer what the actual envvars are.
- It brings little extra value compared to being direct. In fact, it hinders DX, so I question if there are any benefits

### Proposal ("Cand 2")

Summary: Do it direct. That is, deprecate `get_rpc_url_or_exit()` etc. Instead, dfbuyer etc use get_envvar("RPC_URL") directly.

Details...

`pdr_backend/dfbuyer/main.py` would look like:

```python
rpc_url = env.get_envvar_or_exit("RPC_URL")
subgraph_url = env.get_envvar_or_exit("SUBGRAPH_URL")
private_key = env.get_envvar_or_exit("PRIVATE_KEY")
pair_filters = env.get_envvar("PAIR_FILTER")
timeframe_filter = env.get_envvar("TIMEFRAME_FILTER")
source_filter = env.get_envvar("SOURCE_FILTER")
owner_addresses = env.get_envvar("OWNER_ADDRS")
```

### TODOs (if we use Cand 2)

- [ ] In env.py, deprecate `get_rpc_url_or_exit()` etc
- [ ] dfbuyer use get_envvar("RPC_URL") directly.
- [ ] predictoor ""
- [ ] trader ""
- [ ] trueval ""
- [ ] publisher "" (if ready)
