### ISSUE TITLE
[UX, SW Eng] YAML & CLI

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#370]
# DoD 1/2: YAML

ppss.yaml file for everything. Therefore there's 0 friction porting the setup from sim to bots. Problem definition (pp) & solution strategy (ss) for each category as needed. Checked = done in the branch.

- [ ] network specification, for each of: sapphire-testnet, sapphire-mainnet, barge-pdrbot, barge-pytest, (maybe more)
  - network_pp: subgraph_url, rpc_url, owner_addresses, more
  - web3_ss: (maybe): gas strategy, ..
- [x] data
  - data_pp: data problem definition: What feed to predict (for each timeframe: exchanges | ohlcv subset | pairs), more
  - data_ss: data solution strategy What feeds as inputs for model (exchanges | ohlcv subset | pairs), more.
- [x] simulation: pp & ss, as needed
- [ ] all agents: pp & ss for each, as needed
  - [x] predictoor 1
  - [ ] predictoor 2
  - [x] predictoor 3
  - [ ] trader 1
  - [ ] trader 2
  - [ ] dfbuyer
  - [ ] publisher
  - [ ] trueval
  - [ ] payout
- [ ] Result: all envvars deprecated, except PRIVATE_KEY

# DoD 2/2: CLI

CLI for everything. Modeled after df-py's `dftool`. '[]' means optional. If `yaml_file` not specified, it uses the default `ppss.yaml`. 

- [ ] help: `pdr [help]`
- [ ] simulation. `pdr sim [yaml_file]` (`[]` means optional)
- [ ] all agents
  - [ ] predictoor (instrs in predictoor.md)
  - [ ] trader (instrs in trader.md)
  - [ ] dfbuyer
  - [ ] publisher
  - [ ] trueval
- [ ] get predictoor bot performance data (predictoor-data.md)
- [ ] claim payout (instrs in payout.md)
 
# Appendices

### Appendix: Issues that this epic contributes to 
  
Larger issues:
- Contributes: [#231](https://github.com/oceanprotocol/pdr-backend/issues/231)  [Sim, Trader bot] easy sim --> trader bot flow; better backtesting
- Contributes: [#232](https://github.com/oceanprotocol/pdr-backend/issues/232) [Sim, Pdr bot] easy sim --> pdr bot flow; better backtesting

Smaller issues:
- Closes: [#352](https://github.com/oceanprotocol/pdr-backend/issues/352) [SW eng] High DRY violation in test_predictoor_agent.py <> test_predictoor_agent3.py

### Appendix: YAML design notes

Introduce new config file `ppss.yaml`
- It has sections for data_pp, data_ss, model_ss, trade_pp, trade_ss, sim_ss. Each of those fills out as needed.
- Use it for all of (a) sim (b) pdr bot (c) trader bot
- Q: where to invoke?
- A: inside (a)(b)(c). Each opens ss.yaml and use directly. 
- Analysis: This is quite clean compared to envvars; very little custom mucking around

Alt approach: envvars. See appendix below.

### Appendix: Prototype of ppss.yaml

- Note the compact yet super-flexible way to specify `predict_feed` and `input_feeds`

```yaml
data_pp:
  timeframe: 1h
  predict_feed: binance c BTC/USDT
  test_n : 200 # sim only, not bots

data_ss:
  st_timestr: 2019-09-13_04:00
  fin_timestr: now
  max_n_train: 5000
  autoregressive_n : 10
  input_feeds :
    - binance ohlcv BTC/USDT
    - binance c ETH/USDT,TRX/USDT,ADA/USDT
#    - binance c DOT/USDT
    - kraken ohlcv BTC/USDT

model_ss:
  approach: LIN

trade_pp: # sim only, not bots
  fee_percent: 0.0
  init_holdings:
    - 100000 USDT

trade_ss:
  buy_amt: 10 USDT

sim_ss:
  do_plot: True
```

### Appendix: alt option: envvars

An alt option was: have the 10+ settings as envvars. 

- Put settings for data_pp etc into an envvar file `.ppssrc`. Each has envvars like DATA_PP_TIMEFRAME.
- Use it for all of (a) sim (b) pdr bot (c) trader bot
- Q: where to invoke?
- A: run `source .ppssrc` before running (a)(b) or (c). Then inside (a)(b) or (c) the first thing they do is read the envvars.
-  Analysis: This was ok, but it gets sloppy for specifying which input feeds. And
