### ISSUE TITLE
UX+: Analytics for predictoors & traders, to answer "How much $ am I making" then drill in

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#380]
### Background / motivation

Our core users are predictoors & traders who use our pdr-backend python bots. We want to reduce friction for them. 

Even though they operate largely in python-land, there are things we can do in the webapp to help them out.

Top (or near top) of the list is to help them answer the Q: "How much $ am I making / losing". There are many drill-down Q's that emerge from that.

This issue covers both traders & predictoors, because there will be overlap.

One of the key drill-downs will be: In pdr-backend, a README showing how to read logs of each remote agent

### TODOs

- [x] Explore top-level Q's, and drill-down Q's. Along with possible ways to visualize. And wher
  - [x] For traders
  - [x] For predictoors
  - [x] For both 
- [ ] Get feedback from Trent, Roberto, (more?)
- [ ] Ensure that making logs accessible are part of the design
- [ ] Build it. Data flow includes: fetch data, calculate values, render data & values in dashboard
 
### Related

- [pdr-web#48](https://github.com/oceanprotocol/pdr-private/issues/48) is "[Predictoor FE] Backlog". It has some analytics-related issues. _This_ issue needs to reconcile with that.
- [pdr-web#66](https://github.com/oceanprotocol/pdr-web/issues/66) is "Predictoors Leaderboard". It's likely a subset of this, but useful to keep open for now because we'll almost certainly want to highlight the leaderboard; and we want to ensure that it doesn't get missed
- (closed - duplicate) [pdr-private#38](https://github.com/oceanprotocol/pdr-private/issues/38) is "Fetch, visualize and monitor prediction metrics". There was overlap between that issue and this one. So we closed pdr-private#38.
