### ISSUE TITLE
[EPIC] {Mock, real} trades on {historical, live} data, by updating sim_engine & trader

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#387]
### Target outcome

xpmt_engine (nee sim_engine)(xpmt = "experiment") should support these flows:
- Mock trade on historical price feeds. Therefore always local predictions
- Mock trade on live price feeds, local predictions
- Real trade on live price feeds, local predictions

Pdr bots + trader bots + a network should support these flows: (ie they don't need to be in sim_engine / xpmt_engine)
- Mock trade on live price feeds, network/contract predictions
- Real trade on live price feeds, network/contract predictions

### TODOs

Pre-requisite:
- [x] Trader kinda smells now. Refactor it to smell less.

Features needed to support the xpmt_engine flows:
- [x] Rename sim_engine -> xpmt_engine, sim_ss -> xpmt_ss, etc.
- [ ] **In trader bot, support for mock trading.** So that trader bot now supports two flows: {mock trade on live price feeds, real trade on live price feeds}. 
  - in YAML, `trader_ss` gets a new attribute `tradetype`. Value can be `livemock` or `livereal`,for {mock trade on live price feeds, real trade on live price feeds} respectively. Default is `livereal`. The labels `tradetype`, `livemock`, and `livereal` are chosen for consistency with xpmt_engine; its details are below.
  - `pdr trader` CLI has an additional optional arg: `--tradetype=livemock|livereal`. If it's specified in CLI, it overrides the YAML setting.
  - how to implement: where we currently call to a ccxt exchange's "buy" or "sell": override with a fake "buy" or "sell". It still uses ccxt exchange live data as-is. Note: make this easy to use, as xpmt_engine will use it to.
  - logging remains like before, except it notes whether "livemock" or "livereal".
  - need to update READMEs/trader.md too. Include that `mock` is like a "dry run" or "backtesting".
- [ ] **In xpmt_engine, add support for livemock & livereal trading.** So that xpmt_engine supports three flows: {mock trade on historical price feeds, mock trade on live price feeds, real trade on live price feeds}. 
  - in YAML, `xpmt_ss` gets a new attribute `tradetype`. Value can be `histmock`, `livemock` or `livereal`, for {mock trade on historical price feeds, mock trade on live price feeds, real trade on live price feeds} respectively. Default is `histmock`, because it runs super-fast. 
  - `pdr xpmt` CLI has an additional optional arg: `--tradetype=histmock|livemock|livereal`. If it's specified in CLI, it overrides the YAML setting.
  - how to implement: will mean updating `XpmtEngine.do_buy()` and `do_sell()` to support mock & real trades on live price feeds (in addition to status quo mock trades on historical price feeds). And ancillary things.
  - ensure no DRY violations with trader agent code. This will be easy if we have an easy-to-use module for overriding the call to ccxt exchange's "buy" or "sell".
  - need to update the "xpmt" sections in READMEs/predictoor.md and READMEs/trader.md too. Likely a tiny update. Like now, the "xpmt" section in each README should remain identical. Include that mock is like a "dry run" or "backtesting".
  - note: the trading strategy itself can remain naive: buy if predict up / sell if predict down / sell 5 min later.

### Appendix: Motivation for "live trading in sim flow"

Status quo pdr sim flow allows us to rapidly iterate on a simulation setting, with fewer constraints than a predictoor/trader bot flow: continuous-valued predictions, rolling predictions, merging of predicting & trading into one process, predicting & trading on any feed (not just ones on smart contracts).

It would be useful to take these benefits to live trading too. It won't take much work to do this. It will help us go faster wrt "make $" goal.

Then the means to develop algs is: sim flow -> sim flow w live trading -> pdr bot or trader bot flow.
- sim is fastest, iterate most there
- then try it out on live trading (_this is the new part_)
- then change things as needed for pdr bot & trader flow. Eg publish new feeds
- then run pdr bot or trader bot flow

**Comment by trentmc** [comment]
Some useful input from @trizin, from slack:

**> Trader is able to get predictions from smart contracts or from a local predictoor**

I don't see much value in adding this feature. Trader is meant to be used by traders, it should use the agg_predval from the smart contract.

**> Mock trade on historical agg-predvals fetched from mainnet**

I think this'd be one of the most important features and could provide "proof of profitability":
- Get the aggpredval for last x epochs from the subgraph mainnet
- Simulate trades on these epochs and aggpredvals
- Results :yay:

**Some comments:**
- **Mock trade/ Real trade** - perhaps we can just call it --dry-run?
- **local predictions/ network/contract predictions** - this means being able to specify the network in pdr command, right? Barge will have random predictoors running if you pass the flag

imo it's better to keep predictoor and trader separated. predictoor should not care how profitable the trader algo is and solely focus on the accuracy of the signal

**Comment by trentmc** [comment]
@calina-c I believe this issue is done, right?

**Comment by trentmc** [comment]
Closing it; if it should still be open please re-open @calina-c
