### ISSUE TITLE
[Sw eng] Remove DRY violations of ex-scripts

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#412]
### Background / motivation

Pre-requisite: re-merge YAML [#400](https://github.com/oceanprotocol/pdr-backend/issues/400)

There used to be a directory scripts/. The py scripts in this directory had large DRY violations, and other issues too.

As part of the YAML-CLI work, we migrated all scripts into the CLI. During the migration, I cleaned some them up a bit. But there's still more to go.

That's the aim of this issue.

### TODOs

Clean up...
- [ ] util/topup.py
- [ ] util/check_network.py
- [ ] util/get_predictoor_info.py

**Comment by trentmc** [comment]
@idiom-bytes @calina-c there's been a lot of cleanup work since this issue was created.

Do the files above still need work? (They're in different locations now).
