### ISSUE TITLE
[YAML branch] New CLI command for pdr traction: # predictoors vs time, # OCEAN staked vs time, more

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#421]
### Background / motivation

(This is a placeholder until we have a fancier pdr-analytics tool.)

I'm interested in the usage, and growth in usage, of the predictoor system. Just basic stuff here.

These are:
- unique predictoors over time
- unique predictoors daily
- OCEAN staked in system over time (sample random epochs for staked amount)

### TODOs for this issue
- [x] extends from YAML-CLI branch
- [x] Create a new CLI command for this. 
- [x] It grabs relevant subgraph info, calculates required dataframe, plots charts using matplotlib
- [x] predictoor traction charts are delivered
- [x] renamed cli and functions to `...predictoor_traction...`
- [ ] stake-in-system charts are delivered
- [x] ported contract_predictions summary functionality from #374
- [ ] test coverage for: cli commands, calculation modules, subgraph utils

### Resources
See [this slack thread](https://oceanprotocol.slack.com/archives/C051UV3J3T4/p1701248394412269)

### Additional metrics
- (maybe) total OCEAN spent by non-df buyers over time

**Comment by idiom-bytes** [comment]
Notes
(1) Rather than working towards analytics implementation in this ticket, I have reviewed the code and maintained a similar style as get_predictoor_info.py. We can review these patterns and iterate more on pdr-analytics as we work towards that repo.

(2) I have drawn these as daily aggregate charts:
1. cum_sum_ocean_staked
2. cum_sum_unique_predictoor_addresses

From the dataframe, we should also be able to get daily metrics (rather than daily cum_sum), but I have started with these.

**Comment by idiom-bytes** [comment]
Done:
- pdr tool runs, gets all records from subgraph, transforms data into dataframe, and renders 2 cum_sum charts
- test verifies that list of `Predictions` are transformed into the expected dataframe, with the right shape

![cum_sum_stake](https://github.com/oceanprotocol/pdr-backend/assets/69865342/7cb1eb1b-7204-42b7-a6fd-a708606a8ed9)
![cum_unique_predictoors](https://github.com/oceanprotocol/pdr-backend/assets/69865342/abf28020-360d-4c24-a694-bf9ff3073750)

**Comment by idiom-bytes** [comment]
e2e run: `python3 pdr get_system_info 2023-10-01 2023-11-29 my_ppss.yaml sapphire-mainnet` has roughly 630k records. looking forward to moving this to data_eng/factory, such that we can save/load/re-use this data

![image](https://github.com/oceanprotocol/pdr-backend/assets/69865342/36daebf7-46e7-421f-8b72-070cf8871667)

**Comment by idiom-bytes** [comment]
The code for daily users/stake, is very close to cum_sum, therefore I solved for that as well.

I have also:
- Adjusted args such that CONTRACT_ADDRS is optional, supports 1, or multiple
- Added CSVS args such that charts are yielded to `csvs/charts/`

![daily_stake](https://github.com/oceanprotocol/pdr-backend/assets/69865342/33b0971c-c145-4f32-ba50-76b9bdc70076)
![daily_unique_predictoors](https://github.com/oceanprotocol/pdr-backend/assets/69865342/928ea84e-7026-48c1-ae69-d133027fad6f)

**Comment by trentmc** [comment]
At a glance, this looks great. Great work!

> "Cumulative stake vs time", "Daily OCEAN staked"
The meaning of cumulative is a bit ambiguous, and less useful because people will unstake then restake.

It would be more informative to show "total OCEAN stake _currently in system_, vs time". To calculate: for each day, take a few snapshots of OCEAN staked at specific epochs and average it; that's your value for a given day.

> "Cumulative unique users vs time"
This is useful. Let's tweak labels. Our interest here is to track # predictoors, not # traders. And one user may have >1 addresses. Therefore, please please re-label "users" -> "predictoor addresses".

> "Daily # unique users"
Please re-label to "Daily # unique predictoor addresses"

> merge/update code from https://github.com/oceanprotocol/pdr-backend/pull/374/files such that it uses pdr cli and ppss/web3, to leverage the subgraph_url, and more.

A request, please: review this PR, and work with Mustafa to get it merged into main. Then sync the YAML-CLI2 branch with main and resolve conflicts (likely a half-rewrite needed because of CLI). With this done, you can leverage them in your work here.

**Comment by trentmc** [comment]
> The following charts are generated with this run
> `python3 pdr get_system_info 0x30f1c55e72fe105e4a1fbecdff3145fc14177695 2023-10-08 2023-11-30 csvs/ my_ppss.yaml sapphire-mainnet`

You know, if you do `export PATH=$PATH:.`, then you can call pdr directly, ie `pdr get_system_info 0x30f1c55e72fe105e4a1fbecdff3145fc14177695 2023-10-08 2023-11-30 csvs/ my_ppss.yaml sapphire-mainnet`

**Comment by idiom-bytes** [comment]
```A request, please: review this PR, and work with Mustafa to get it merged into main.```
100%

```Then sync the YAML-CLI2 branch with main and resolve conflicts (likely a half-rewrite needed because of CLI). With this done, you can leverage them in your work here.```
With these latest updates, I have now used little of that work, and have improved in many other areas. I'll iterate @kdetry and get things ready.

**Comment by trentmc** [comment]
One more feedback: "get_system_info" is too general of a label. Better is: "get_predictoor_traction". (If you think of something even more precise, go for it.)

**Comment by idiom-bytes** [comment]
sounds great, i'll rename it to that when i resume
