### ISSUE TITLE
[EPIC] [YAML] Well-structured lake & analytics

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#447]
### Background / motivation
This is an epic to mature our pipeline for data going into the data `lake/`, and for consuming it in `analytics/`. By the end, the lake, etl, and analytics should only fetch/update whats needed. 

Most calculations and aggregations should be done at the ETL level, yielding tables that have been tested and verified. Core analytic tables (parquet) will be created as a result of data_factory + ETL doing their work. 

Analytics and other modules should then consume from the local lake/tables (like a database). Analytics, reports, streamlit should mostly, just consume/report from the work done by the ETL.

Steps Proposed are:
1. Lake Preparation
2. ETL + Bronze Data Workflow
3. Cleanup Table Interface

![image](https://github.com/oceanprotocol/pdr-backend/assets/69865342/70ac076e-7e75-41a6-acda-329131b3185d)

### 1. Lake Preparation
- [x] Rename/move files & dirs for proper separation among lake, AI models, analytics [#446](https://github.com/oceanprotocol/pdr-backend/issues/446)
- [x] predictoor_stats.py - remove `get_endpoint_statistics  [#477](https://github.com/oceanprotocol/pdr-backend/issues/477) 
- [x] Move logic from subgraph_slot.py [#483](https://github.com/oceanprotocol/pdr-backend/issues/483)
- [x] Integrate pdr_subscriptions into GQL Data Factory [#468](https://github.com/oceanprotocol/pdr-backend/issues/468)
- [x] Update gql_data_factory tests/logic to handle more complex cases: multiple queries/parquet files, no records to fetch, non-existing parquet, different start/end records. [#468](https://github.com/oceanprotocol/pdr-backend/issues/468)
- [x] Re-write get_cli_statistics() into 2 fns and to use polars [#453](https://github.com/oceanprotocol/pdr-backend/issues/453)
- [x] predictoor_stats.py - remove `aggregate_prediction_statistics` was completed in [#453](https://github.com/oceanprotocol/pdr-backend/issues/453)

At a later date, update `accuracy/app.py` to use data_lake + ETL.
Review peripheral/utilities that might be good candidates for using lake/etl data.

### ETL + Bronze Data Workflow
Due to how subgraph works, we need to be smart about how to keep our local records up-to-date. The simplest, dumbest way is to fetch all: predictions/truevals,payouts, and join them into a table <bronze_post_pdr_predictions_table>.

**Part A - Integrate all raw data**
- [x] Modify data_factory._update() to only fetch/update predictions that have changed. pdr data_factory._update() fetches new predictPredictions (prediction state) that were computed by subgraph.
- [x] Integrate truevals into gql_data_factory [#480](https://github.com/oceanprotocol/pdr-backend/issues/480)
- [x] Integrate payouts into gql_data_factory [#481](https://github.com/oceanprotocol/pdr-backend/issues/481)

**Part B - Do ETL + Bronze Tables**
- [x] Create etl.py such that GQLDataFactory() creates the raw data, while ETL() is responsible for the steps required to evolve the data from raw, to bronze, and beyond. => [#482](https://github.com/oceanprotocol/pdr-backend/issues/482)
- [x] Create a clean "bronze_predictions" table using all source raw tables: (1) predictions, (2) truevals, (3) payouts by slot) => [#482](https://github.com/oceanprotocol/pdr-backend/issues/482)

### 3 - Cleanup Table Interface
- [x] Create a Table base object, so save/load/query functionality isn't duplicated across GQLDataFactory/ETL [#593](https://github.com/oceanprotocol/pdr-backend/pull/593)
- [x] Move Tables() out of GQLDataFactory/ETL, so other classes/actors can access them. [#593](https://github.com/oceanprotocol/pdr-backend/pull/593)

**Comment by idiom-bytes** [comment]
Merging ETL [#482](https://github.com/oceanprotocol/pdr-backend/issues/482) should complete this epic.

**Comment by idiom-bytes** [comment]
We have completed this ticket.

We now have ticket [#685](https://github.com/oceanprotocol/pdr-backend/issues/685) for continuing data-engineering / data-pipeline work w/ DuckDB.

We also have ticket [#618](https://github.com/oceanprotocol/pdr-backend/issues/618) for continuing the work w/ aggregating revenue (Predictoor Income), creating the plot, and getting the first dapp page working.

I'm closing this ticket, so we're then focused on completing the DuckDB work, the dapp/analytics work, in addition to the "well-structured lake & analytics" part. Including improving tools & SLA, so it's easier to follow and manage the ETL work/tables.
