### ISSUE TITLE
[Epic][E2e Streamlit]  Create `Feed Overview` streamlit page (expand lake/ + analytics/)

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-backend#478]
# Motivation
As @KatunaNorbert recommended, we should have a clear E2E of what https://github.com/oceanprotocol/pdr-backend/issues/447 is working towards.

get_endpoint_statistics() has many feed_statistics that should be reported somewhere. To avoid adding this as a cli_module to then change it again, let's remove it for now.

This ticket is for revisiting this when creating the "Feed Overview" and "Feed Detail" pages found here: https://docs.google.com/presentation/d/18y_nfpc3e-dop5NtfIisgUkc-oPt8dft9WyAnqhSqZg/edit#slide=id.g28d2e627aad_0_0

This ticket should explain how to create the "Feed" tables inside the Lake, load them from parquet in Analytics, and render them into Streamlit.

At the end, we should have `lake/` creating this data as it updates, and new  "streamlit-single-page-app" should simply consume this data to provide insights on Feeds.

### DoD - Medallion Workflow + Streamlit requirements
- [ ] Design tables, charts, and requirements for the `Feed Overview` + `Feed Details` pages
- [ ] Define table requirements to service `Feed Overview Page`- **gold_pdr_feeds_summary** <feed, timeframe, source> final aggregated metrics to provide an overall summary: total_stake, total_payout, rolling_accuracy.
- [ ] Define table requirements to service `Feed Details Page` - **silver_pdr_feeds** <feed, timeframe, source> per event aggregation to report time-series insights: {sum_staked, n_staked, sum_stake_revenue, sum_stake_slash, sum_df_rewards, sum_rose_rewards, rolling_accuracy, rolling_stake}
- [ ] Build data-workflows for `silver_pdr_feeds` and `gold_pdr_feeds_summary` into ETL.
- [ ] Create Feed Overview streamlit page
- [ ] Add gold_summary as a table
- [ ] Add silver time-series data as charts

**Comment by idiom-bytes** [comment]
Closing this ticket for now. Re-open when we're closer to it.
