### ISSUE TITLE
[Epic][Analytics] Create `Predictoor Income` Streamlit Page

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-backend#479]
# Motivation
As @KatunaNorbert recommended, we should have a clear E2E of what https://github.com/oceanprotocol/pdr-backend/issues/447 is working towards.

After completing our lake + analytics update (https://github.com/oceanprotocol/pdr-backend/issues/447) we should consider our first `streamlit_page.py`. Consider at first the streamlit-app to be composed of many single-page-apps. Each one representing a page/menu. We can then join them via a navbar.

This ticket is for creating the first page: "Predictoor Income" as defined here: https://docs.google.com/presentation/d/18y_nfpc3e-dop5NtfIisgUkc-oPt8dft9WyAnqhSqZg/edit#slide=id.g20f5357f625_0_1639

This ticket should explain how to get all required data from the silver_pdr_predictions table, to create the charts required for the streamlit app.

At the end, we should have `lake/` creating this data as it updates, and new  "streamlit-single-page-app" should simply consume this data to provide insights on Predictoor Income.

### DoD - Medallion Workflow + Streamlit requirements
- [ ] Design tables, charts, and requirements for the `Predictoor Income` page
- [ ] Define table requirements to service `Predictoor Income Page`- **gold_pdr_predictoor_summary** <feed, timeframe, source, predictoor> final aggregated metrics to provide an overall summary: sum_stake, sum_stake_revenue, sum_stake_slash, sum_df_revenue, sum_rose_rewards, ...
- [ ] Define table requirements to service `Predictoor Income Page` - **silver_pdr_predictoor** <feed, timeframe, source> per event aggregation to report time-series insights: sum_stake, sum_stake_revenue, sum_stake_slash, sum_df_revenue, sum_rose_rewards, ...
- [ ] Build data-workflows for `silver_pdr_predictoor` and `gold_pdr_predictoor_summary` into ETL.
- [ ] Create `Predictoor Income` streamlit page
- [ ] Based on requirements - Visualize gold_pdr_predictoor_summary as a table
- [ ] Based on requirements - Visualize silve_pdr_predictoorr table as time-series charts & analytics

**Comment by idiom-bytes** [comment]
This was the old ticket. I have simplified the task further to increase focus on e2e and reduce additional items such as gold tables.
