### ISSUE TITLE
[YAML] Filter by feeds in publisher module

### ISSUE THREAD

**Issue by calina-c** [oceanprotocol/pdr-backend#490]
Parent: [EPIC: YAML] Add YAML & CLI. "v0.2" of Predictoor [#400](https://github.com/oceanprotocol/pdr-backend/issues/400)

### Background / motivation

In "Refine ppss.yaml for closer 1:1 mapping to bots" [#451](https://github.com/oceanprotocol/pdr-backend/issues/451), the yaml file got reworked. The big change was: each module got its own "ss" module, with parameters specified via a sub-section of ppss.yaml. Then, most modules got their own way to specify feeds. Because modules earlier in the flow may have more feeds (eg ohlcv data factory), and modules later on may have fewer (eg predictoor).

Exception: one module isn't done yet: publisher. That's the goal of this issue.

Specifically, to specify to publisher what feeds to publish, we need to move from its status quo of hardcoded list of feeds, to a list of feeds specified in publisher_ss.

### Details:

In ppss.yaml, there is already:
```text
publisher_ss:
  sapphire-mainnet:
    fee_collector_address: 0x0000000000000000000000000000000000000000
  sapphire-testnet:
    fee_collector_address: 0x0000000000000000000000000000000000000000
  development:
    fee_collector_address: 0x0000000000000000000000000000000000000000
```

A `feeds` section needs to get added to that:
```
[publisher_ss:]
  feeds:
    - 5m binance BTC/USDT
#    - 1h binance BTC/USDT
#    - 5m binance BTC/USDT ETH/USDT BNB/USDT XRP/USDT ADA/USDT DOGE/USDT SOL/USDT LTC/USDT TRX/USDT DOT/USDT
```

Then, publisher module needs to read in publisher_ss.feeds, and choose what to publish based on that.

Publisher will _not_ be doing subgraph queries from existing feeds. Rather, it is publishing new feeds.

Note that most module ss's _inherit_ a base ss in order to get `feeds` functionality in a single line. We should be able to do the same thing here. Of course we still need to update publisher behavior, and add tests.

### TODOs

- [ ] Update ./ppss.yaml to have example feeds in publisher_ss section
- [ ] Update publisher_ss to handle feeds
- [ ] Update publisher to use publisher_ss feeds (and deprecate old hardcoded way)
- [ ] Ensure all tests are up to date

**Comment by trentmc** [comment]
Done in PR https://github.com/oceanprotocol/pdr-backend/pull/533
