### ISSUE TITLE
[Lake] Integrate dydx into fetch_ohlcv.py & ohlcv_data_factory.py

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-backend#493]
### Motivation

Parent epic: [#492](https://github.com/oceanprotocol/pdr-backend/issues/492) "Explore DYDX towards making money: data_factory, trader, sim, and predictoor".

### TODOs

- [x] [Step 1] Rename fetch_ohlcv.py::safe_fetch_ohlcv() -> `safe_fetch_ohlcv_ccxt()`. Ensure all tests pass. Merge PR into main. Update: done in commit https://github.com/oceanprotocol/pdr-backend/commit/54b7038e1b68b0c1f39c49a1d5fb548a393f0b08
- [x] [Step 2] In fetch_ohlcv.py, add a new method `safe_fetch_ohlcv_dydx()`. Add unit test(s) in test_fetch_ohlcv.py. Update: done in commit https://github.com/oceanprotocol/pdr-backend/commit/188d0221581d2c3ff0e444de26ae41531a4e4239
  - [x] Build functionality && Test: Happy path of fetching data without problems
  - [x] Test: Gracefully handle nan values (vs floats). Update functionality as needed.
  - [x] Test: Handle when coin or pair doesn't exist. ""
  - [x] Test: Handle when bad start date or end date. ""
  - [x] Test: Is there a limit on # points at once? (eg 1000). ""
  - [x] Merge PR into main.
- [ ] [Step 3] In fetch_ohlcv.py, add a new method `safe_fetch_ohlcv()` which takes in a specified exchange name, and passes through to either `safe_fetch_ohlcv_ccxt()` or `safe_fetch_ohlcv_dydx()`, depending on the exchange name. Add unit test(s). Merge PR into main.
- [ ] [Step 4] Update ohclv_data_factory.py::OhlcvDataFactory._update_rawohlcv_files_at_feed() to use the (new) `safe_fetch_ohlcv()` interface, which means it will naturally support ccxt or dydx

**Comment by graceful-coder** [comment]
Completed PR 1 of 4: #666
