### ISSUE TITLE
[EPIC] Ship MVP. Incl remote networks, sys-level flows, hardening 

### ISSUE THREAD

**Issue by trizin** [oceanprotocol/pdr-backend#50]
(Ordered from highest to lowest priority)

**Phase: Harden 1**
- [x] [Berkay] Some epochs might not get truevals; fix this [#3](https://github.com/oceanprotocol/pdr-backend/issues/3)
- [x] Add unit tests & refactor predictoor, trader, trueval agents [#13](https://github.com/oceanprotocol/pdr-backend/issues/13)
- [x] Add unit tests & refactor trader agent [#136](https://github.com/oceanprotocol/pdr-backend/issues/136)

**Phase: Finalize local flows**

- [x] Add local README for each stakeholder (frontend dev, backend dev, predictoor, trader) [#51](https://github.com/oceanprotocol/pdr-backend/issues/51)
- [x] For predictoor stakeholder, enable (a) simple flow with random predictions, yet (b) examples of using actual models [#54](https://github.com/oceanprotocol/pdr-backend/issues/54)

**Phase: In time for remote-testnet**

- [x] Towards remote: Add a README for building and deploying a container image on Azure [#20](https://github.com/oceanprotocol/pdr-backend/issues/20)
- [x] Towards remote: Faucet for testnet tokens [#60](https://github.com/oceanprotocol/pdr-backend/issues/60)
- [x] update READMEs based on Berkay's new azure readmes [#68](https://github.com/oceanprotocol/pdr-backend/issues/68)
- [x] Deploy & get everything running
- [x] Update READMEs for remote testnet, to make it repeatable [#60](https://github.com/oceanprotocol/pdr-backend/issues/60)
- [x] Work with Norbert / frontend team to ensure that test.predictoor.ai is working
- [x] Improve subgraph / query documentation based on current practices [#138](https://github.com/oceanprotocol/pdr-backend/issues/138)
- [x] [Alex] Write a test script that checks status of each agent [#139](https://github.com/oceanprotocol/pdr-backend/issues/139)

**Phase: 60min feeds (pre-req for mainnet)**

- [x] deploy 60min feed contracts on testnet
- [x] deploy & test 60min agents on testnet [pdr-backend#182](https://github.com/oceanprotocol/pdr-backend/issues/182)

**Phase: In time for predictoor-mainnet**

- [x] Execute operational plan for agents/tokens, non-DF aspects [pdr-private#45](https://github.com/oceanprotocol/pdr-private/issues/45). [Plan](https://github.com/oceanprotocol/pdr-private/issues/33#issuecomment-1706518704)
- [x] Predictoor on Sapphire mainnet [pdr-private#31](https://github.com/oceanprotocol/pdr-private/issues/31)
- [x] Update READMEs for remote mainnet [#61](https://github.com/oceanprotocol/pdr-backend/issues/61). Should cover instrs how to get OCEAN (via Celer bridge) and ROSE (via Binance)
- [x] Deploy & test all agents on mainnet. Incl 5min & 60min feeds. Use dynamic-model predictoors. [pdr-backend#183](https://github.com/oceanprotocol/pdr-backend/issues/183) 

**Phase: Harden 2**

- [x] Add Error Handling [#45](https://github.com/oceanprotocol/pdr-backend/issues/45)
- [x] [predictoor] use subgraph to detect and claim unclaimed profits [#10](https://github.com/oceanprotocol/pdr-backend/issues/10)
- [x] Rewrite predictoor approach3 with dynamic modeling (model-based) [#137](https://github.com/oceanprotocol/pdr-backend/issues/137)

**Phase: in time for Predictoor DF**
- [x] Add unit tests & refactor dfbuyer agent [#128](https://github.com/oceanprotocol/pdr-backend/issues/128)
- [x] Review algorithm for how dfbuyer buys [#42](https://github.com/oceanprotocol/pdr-backend/issues/42)
- [skip for this issue, do on its own] Execute operational plan for agents/tokens, including DF aspects [pdr-private#45](https://github.com/oceanprotocol/pdr-private/issues/45). [Plan](https://github.com/oceanprotocol/pdr-private/issues/33#issuecomment-1706518704)

**Other**
- (Now that many of us are actively using pdr_backend, we're also finding many issues and fixing them. Don't bother tracking them here)

**Comment by trentmc** [comment]
All that's left is:

Execute operational plan for agents/tokens, including DF aspects [pdr-private#45](https://github.com/oceanprotocol/pdr-private/issues/45). [Plan](https://github.com/oceanprotocol/pdr-private/issues/33#issuecomment-1706518704)

We can skip that for _this_ issue, and do it on its own.

So, closing! :) :)
