### ISSUE TITLE
Add local README for each stakeholder 

### ISSUE THREAD

**Issue by trizin** [oceanprotocol/pdr-backend#51]
[Part of epic [#50](https://github.com/oceanprotocol/pdr-backend/issues/50) "Ship MVP"]

### What

Add local README for each stakeholder: frontend dev, backend dev, trader, predictoor.

Just do fully-local, for this issue.  [#60](https://github.com/oceanprotocol/pdr-backend/issues/60) is for remote.

### TODOs

Add README for:
- [x] predictoor stakeholders https://github.com/oceanprotocol/pdr-backend/commit/4f571c8ed1a895fe5eab661e5a4a0ccec377e22b
- [x] trader stakeholders https://github.com/oceanprotocol/pdr-backend/commit/656fc558d193f4c3e26916828dc30923f7512d51
- [x] frontend devs https://github.com/oceanprotocol/pdr-backend/commit/42fdba75d33777c630c247dcdee25c080f4ed7a5
- [x] backend devs https://github.com/oceanprotocol/pdr-backend/commit/42fdba75d33777c630c247dcdee25c080f4ed7a5
- [x] publisher https://github.com/oceanprotocol/pdr-backend/commit/4975930954001a8fc90ca997fca908569ab75784, https://github.com/oceanprotocol/pdr-backend/commit/cb70a86217c2611ef8f5446c3afe06925221ca53
