### ISSUE TITLE
[EPIC] Tracer-bullet remote-testnet (first part)

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#55]
### What

Tracer bullet on remote testnet (Sapphire testnet)

### TODOs

Tracer bullet on remote testnet (Sapphire testnet)
- [x] Pre-requisite [#17](https://github.com/oceanprotocol/predictoor-pm/issues/17) "Predictoor Running on Sapphire Testnet"
- [x] Deploy contracts to remote testnet
- [x] Deploy predictoor, trueval, dfbuyer agents and websocket backend on testnet
 
(Remaining steps have been moved to [pdr-backend#50](https://github.com/oceanprotocol/pdr-backend/issues/50) "Tracer-bullet remote-testnet, then MVP"
