### ISSUE TITLE
[Lake, UX] Lake supports >1 writers, incl predictoor bots and >1 pdr lakes

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#564]
### Background / motivation

**Approach 0: each app writes lake, in its process.** Predictoor bot updates the data lake, then uses the lake, in time for making predictions. Same for other apps in pdr-backend. 

**Approach 1: separate lake, started separately** 
- User starts a _separate_ process `pdr lake`. It's constantly writing to the data lake
- Predictoor bot _reads_ from the lake, but does not write (for safety). Same for other apps. 
- This was the idea when we conceived of lake.

But we can do better yet, leveraging the database concept of "locking" which enables >1 writers without hurting DB safety. Writers must handle contention due to locks, eg by waiting.

**Approach 2: allow >1 writers.**
- We could have >1 lake processes / threads, predictoor bots, or other apps. 
- Support two flows:
  - _Flow 1: quickstart:_ start `pdr lake` inside the app. Eg user starts one `pdr predictoor` process (and nothing else).  The predictoor bot will detect whether a lake process is running, and start one if needed.
  - _Flow 2: power-predictoor usage:_ start `pdr lake` separately. Eg a user starts `pdr lake`, then 20 `pdr predictoor` processes, one for each feed to predict
  - _Flow 3: power-lake usage:_ >1 lake processes / threads filling complementary parts of lake (different pairs, different subgraph queries). Eg user starts 1 `pdr lake` process, and it starts >1 threads. Eg user starts 1 process, then later one, a different one with different goals. Eg >1 users start different processes
- Benefits: (a) more convenient: users don't _need_ to kick off the lake process themselves. (b) faster: because parallel fill (c) more flexible: users (or predictoor bots) can start more lake processes without worry

Approach 2 is endgame. The benefits compared to 1 are immense, let alone 0.

Q: Should we go from 0 -> 1 -> 2, or 0->2 directly? 
- I (Trent) recommend the 0->2 directly because of the big benefits
- Whereas doing 1 in between would force the user to have to change behavior. (And extra effort for us overall: much of the code we'd write for 1 would be thrown away for 2)

### TODOs

- [ ] Locking core: Update lake to support "locking" concept. Such that I could run >1 different pdr lake processes against the same feed, and they wouldn't fight with each other
- [ ] Parallel fill: Update lake to run >1 threads within a single pdr lake process, 1 thread per ohlcv pair or subgraph feed
- [ ] Update predictoor bot: detect whether a lake process is running, and start one if needed.
- [ ] Similarly, update xpmt_engine (nee sim_engine) flow
- [ ] Similarly, update analytics apps flows
- [ ] Ensure READMEs are all updated accordingly. predictoor.md and trader.md should teach the user about how to run `pdr lake` separately (at the end of the README)

**Comment by idiom-bytes** [comment]
Hi, I have the same goal of having an ETL worker/workflow that's consistently building out the lake/aggregates, so other systems can read from it.

**However, I'm recommending to KISS.** 
Please, do not set requirements for locking/unlocking/db-like functions. I don't believe this is needed. We just need to follow simple concepts.
1. DataFactories is the only component that writes to disk. 
2. Factories can have many processes, each one responsible for filling a folder in the lake.
3. Similar to a DB, each process is responsible for updating a folder/table.
4. Updates are done by creating a new artifact (table) and then renaming/dropping.
5. All other components read from the latest table.

Recommendation:
(1) No: Let's not build locking/db-like features .
(2) Yes: Build "lake process" (or ETL) to build out the lake.
(3) Yes: Fill the lake w/ "tables" & processes.
(4) Yes: Keeping analytics simple.
(5) Yes: Investing time in expanding the ohlcv data factory to support volume ticks, and efficient f(x).
(6) Yes: Figure out data requirements + pipeline for ohlcv + f(x) + AI.
(7) Yes: Roll requirements and infrastructure to drive AI, into analytics.

Please let's avoid (1). Do not over-complicate the analytics ETL pipeline, YAGNI. It doesn't improve the product or the our revenue. Let's focus more advanced concepts to solve (7) for OHLCV volume ticks, f(x), and trading-related systems.

For product analytics, KISS.

**Comment by idiom-bytes** [comment]
DuckDB only lets you have 1 writer process at a time that holds the db writer connection. Within this, you can then have multiple threads/operating on it. So, for the duckdb "container/process/vm" we should make it as big as possible.

There is now a task for making sure that Lake/ETL has an "update process" that sits there indefinitely looping and updating the lake [#1107](https://github.com/oceanprotocol/pdr-backend/issues/1107)

To solve for "Approach 2" / multiple writers, we would need a cluster (i.e. clickhouse).

**Comment by trentmc** [comment]
Priorities have mostly shifted away from pdr-backend. So closing less-critical issues.
