### ISSUE TITLE
Update READMEs for remote mainnet

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#61]
[Part of epic [#50](https://github.com/oceanprotocol/pdr-backend/issues/50) "Ship MVP"]

### TODOs
- [x] main work: update READMEs for remote mainnet
- [x] include instrs on how to get OCEAN (via mainnet --> Celer bridge)
- [x] instrs how how to get ROSE (via Binance)
