### ISSUE TITLE
[Epic][Lake][Analytics] Create Predictoor Income dashboard

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-backend#618]
### Motivation
We want to go from tables and etl, to dashboards.
The two frameworks we may consider right now are Streamlit and Dash.

### Framework Considerations
**Dash** is OSS, fully fledged so, it delivers things like url routing out of the box.
It also has enterprise support, so there is that potentially unblocking limitations we may hit.
https://dash.plotly.com/

**Streamlit** is leaner, w/ more community projects/plugins used to solve individual needs
Things like routing are additional, and require development.
https://discuss.streamlit.io/t/is-there-a-way-to-have-multiple-pages-like-flask/16823

I originally used Streamlit because I like it's native matplotlib and python graphing library support.
However, I'm not sure how uphill it will be to achieve some basic functionality.
My recommendation is to start w/ Dash + Plotly, to reduce UI bottlenecks.

### DoD:
Prepare Data:
- [ ] Update bronze_prediction table to calculate Predictoor Income parameters
- [ ] Create silver_table that aggregates by [user_id, contract_id]: sum_stake_revenue, sum_df_revenue, ...

Create First Plot + Filter and Single Page App:
- [ ] Create initial plotly plot for [Predictoor Income Dashboard]
- [ ] Design plot to support multiple [user_id] addresses, returning the sum across all [user_id] addresses
- [ ] Embedd initial [Predictoor Income Plot] into web UI framework.
- [ ] Add address filtering so you can pass multiple addresses, test performance
- [ ] Sign off on plotly + web framework

Create Second Plot + Filter for Single Page App:
- [ ] Create remaining plots for [Predictoor Income Dashboard]. (check analytics slides)
- [ ] Update plot design to support multiple [contract_id] addresses, returning the sum across all [user_id, contract_id] addresses
- [ ] Embedd remaining plots for [Predictoor Income Dashboard] into web UI framework
- [ ] Add contract-based filters (address, timeframe, asset)
- [ ] Test plot performance, and sign off

We should now have a

**Comment by trentmc** [comment]
pdr analytics prototypes in GSlides:
https://docs.google.com/presentation/d/18y_nfpc3e-dop5NtfIisgUkc-oPt8dft9WyAnqhSqZg/edit#slide=id.g20f5357f625_0_1545

**Comment by idiom-bytes** [comment]
**[Frameworks & Plots]**
Based on previous history, I estimate the team will feel that:
- matplotlib is too detailed
- streamlit is too vanilla

As I mentioned in chats, I'm recommending the least amount of time getting a basic plot/app in place to stress test it.

This means plotly/streamlit.

**Comment by idiom-bytes** [comment]
@KatunaNorbert please note that I updated the table design/schema, such that the calculated tables + aggregates are taking place at the silver-level.

This is such that our bronze_tables remain: "close-to-raw, clean"
While silver tables remain: "enriched + aggregated"

**Comment by KatunaNorbert** [comment]
Got it, sound good @idiom-bytes

**Comment by trentmc** [comment]
Recall our recent conversation why we don't want to use "Dashboard" label: 
- "Dashboard" implies a relatively static set of plots, with little interactivity and only mild discovery (browse, search, filter). 
- Whereas what we want is a _dapp_ that has highly interactive plots and powerful discovery.

Accordingly, in this issue's title and description, I replaced "Dashboard" with "dapp" & "dapp with plots". Please ensure other issues follow this too. Thank you:)

**Comment by idiom-bytes** [comment]
Updating tickets...
- This work has been completed using polars + streamlit.
- We need to complete the work w/ duckdb + dash in order to get this working w/ latest. This is still the target.
