### ISSUE TITLE
[Sim] Log & plot predicting $ made

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#661]
### Background / motivation

Right now the simulator does logs and plots for: (a) predictions % correct vs time and (b) trading $ made. The appendix gives examples. An example line is: `Iter #196/200: ut=1708590600000, dt=2024-02-22_08:.. Preddir|true|correct = UP|DN|N. Total correct 97/196 (49.5%), profit $  -0.68}, tot_profit $    -5.79`

But sim does _not_ have logs or plots for "predicting $ made". This would be highly useful.

Q & A:
- Q: how to account for $ revenue? 
- A: in `predictoor_ss: sim_only: `, specify `weekly_revenue_amount` (denominate in OCEAN)
- Q: how to account for other predictoors? 
- A: specify `predictoor_ss: sim_only: `, specify `others_stake_amount` (denominate in OCEAN). Related, we must move `stake_amount` one level up from `bot_only`, since it's applicable to sim too.

### TODOs

- [x] Update ppss.yaml, predictoor_ss.py, test_predictoor_ss.py to support:
  - [x] In `predictoor_ss: sim_only: `, add `weekly_revenue_amount` (denominate in OCEAN) 
  - [x] In `predictoor_ss: sim_only: `, specify `others_stake_amount` (denominate in OCEAN)
  - [x] In `predictoor_ss: sim_only: `, specify `others_percent_stake_correct` 
  - [x] In `predictoor_ss:`, move `stake_amount` one level up
- [x] In sim, change status quo "profit" logs to explicitly state it's for _trader_
- [x] In sim, change status quo "profit" plot to explicitly state it's for _trader_
- [x] In sim, add "profit" logs for _predictoor_. It will take into account the PPSS updates, and will likely have to track more info.
- [ ] In sim, add "profit" plot for _predictoor_.

### Appendix: status quo sim log

`pdr sim` logs like this:
```text
2024-02-22 09:52:50,027 INFO Iter #194/200: ut=1708590000000, dt=2024-02-22_08:.. Preddir|true|correct = UP|DN|N. Total correct 97/194 (50.0%), profit $  -1.21}, tot_profit $    -4.96
2024-02-22 09:52:50,046 INFO TX: BUY : send  1000.00 USDT, receive     0.02 BTC, fee =   0.0000 USDT
2024-02-22 09:52:50,046 INFO TX: SELL: send     0.02 BTC, receive   999.85 USDT, fee =   0.0000 USDT
2024-02-22 09:52:50,046 INFO Iter #195/200: ut=1708590300000, dt=2024-02-22_08:.. Preddir|true|correct = UP|DN|N. Total correct 97/195 (49.7%), profit $  -0.15}, tot_profit $    -5.11
2024-02-22 09:52:50,058 INFO TX: BUY : send  1000.00 USDT, receive     0.02 BTC, fee =   0.0000 USDT
2024-02-22 09:52:50,058 INFO TX: SELL: send     0.02 BTC, receive   999.32 USDT, fee =   0.0000 USDT
2024-02-22 09:52:50,058 INFO Iter #196/200: ut=1708590600000, dt=2024-02-22_08:.. Preddir|true|correct = UP|DN|N. Total correct 97/196 (49.5%), profit $  -0.68}, tot_profit $    -5.79
2024-02-22 09:52:50,131 INFO Iter #197/200: ut=1708590900000, dt=2024-02-22_08:.. Preddir|true|correct = DN|UP|N. Total correct 97/197 (49.2%), profit $   0.00}, tot_profit $    -5.79
2024-02-22 09:52:50,144 INFO Iter #198/200: ut=1708591200000, dt=2024-02-22_08:.. Preddir|true|correct = DN|UP|N. Total correct 97/198 (49.0%), profit $   0.00}, tot_profit $    -5.79
2024-02-22 09:52:50,158 INFO Iter #199/200: ut=1708591500000, dt=2024-02-22_08:.. Preddir|true|correct = DN|UP|N. Total correct 97/199 (48.7%), profit $   0.00}, tot_profit $    -5.79
2024-02-22 09:52:50,174 INFO Iter #200/200: ut=1708591800000, dt=2024-02-22_08:.. Preddir|true|correct = DN|UP|N. Total correct 97/200 (48.5%), profit $   0.00}, tot_profit $    -5.79
2024-02-22 09:52:50,230 INFO Done all iters.
2024-02-22 09:52:50,230 INFO Final nmse_train=0.00007, nmse_test=0.00779
```

### Appendix: status quo sim plot
![Screenshot 2024-02-22 at 09 52 45](https://github.com/oceanprotocol/pdr-backend/assets/5305452/8915ef8a-9c12-49bb-9f77-5c32e60d2489)
