### ISSUE TITLE
[Sim] Implement two-sided prediction into sim_engine

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#668]
### Background / motivation

- In [#661](https://github.com/oceanprotocol/pdr-backend/issues/661) "[Sim] Log & plot predicting $ made", we added logs & plots for profitability of predictoors. It's clear that one-sided prediction is not competitive.

What would be really useful: a two-sided prediction paradigm in sim_engine.

### TODOs

- [ ] add a classifier for confidence level of up vs down
- [ ] for sim_engine's predictoor bots: model two-sided prediction
- [ ] for sim_engine's trader bots: use up/down confidence level to decide amt of $ to put in

**Comment by trentmc** [comment]
Closing as duplicated: moved this into [#599](https://github.com/oceanprotocol/pdr-backend/issues/599)
