### ISSUE TITLE
[UX] Write blog post on two-sided prediction bots, and updated sim_engine

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#679]
### Background / motivation

[#599](https://github.com/oceanprotocol/pdr-backend/issues/599) implemented two-sided prediction into sim_engine, pdr bot 1, and pdr bot 2 (nee 3).

It will be useful to share a bit more info about what this is, to our users.

### TODOs

- [ ] Write draft blog post. Content to include
  - [ ] Explain motivation of two-sided prediction. Lower variance -> higher profitability
  - [ ] How to use it: sim & predictoor bot. Two private keys
  - [ ] New sim_engine plots
- [ ] Publish blog post
- [ ] Tweet about it
