### ISSUE TITLE
[EPIC] Two-sided prediction bots

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#680]
### TODOs

- [x] Implement two-sided prediction into sim_engine, pdr bot 1, and pdr bot 2 (nee 3) [#599](https://github.com/oceanprotocol/pdr-backend/issues/599) 
- [x] Update k8s for two-sided prediction bots [#678](https://github.com/oceanprotocol/pdr-backend/issues/678) 
- [x] Do new release of pdr-backend: v0.3
- [x] Write blog post on two-sided prediction & sim_engine plots [#679](https://github.com/oceanprotocol/pdr-backend/issues/679)
