### ISSUE TITLE
[Lake][ETL] DuckDB E2E - Ingestion -> Dashboards

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-backend#685]
### Motivation
We completed the techspikes around our data infrastructure. As an outcome, we're going to implement our ETL pipeline in DuckDB such that we maintain many of our constraints:
- We can test everything end-to-end (pytest, duckdb, plots)
- We can reduce requirements on servers/infra/ops by using in-memory, embedded, on-disk db (duckb)
- We can continue doing distributed computing (ray)
- DB store can grow elastic w/ lvm, efs, filestore

### Outline
**Our first goal is to take the current ETL workflow and update it end-to-end.**

![Screenshot from 2024-02-29 13-51-46](https://github.com/oceanprotocol/pdr-backend/assets/69865342/8dc020e2-cf53-49d8-8327-9afc222e1750)

### Shelved Deliverables
CLOSED TICKET - Add ETL checkpoint to enforce SLAs, and process data incrementally. [#694](https://github.com/oceanprotocol/pdr-backend/issues/694)

Reason: We're going to instead implement a build step that leverages a simple SQL strategy w/ temp tables, such that we can enforce SLAs in a clean manner.

## DoD
**[First Deliverable - Update Ingestion + Load]**
- [x] Update GQL local/save-to-disk to use csv [#681](https://github.com/oceanprotocol/pdr-backend/issues/681)
- [x] Fetch + insert new records into db [#682](https://github.com/oceanprotocol/pdr-backend/issues/682)

**[Core System Updates]**
- [x] Improve ETL by using SQL build strategy & temp tables to enforce SLAs [#771](https://github.com/oceanprotocol/pdr-backend/issues/771)

**[Update ETL Deliverables]**
- [x] DuckDB - Update existing logic that queries data from parquet using polars, to query_data from PersistentDataStore using SQL.
- [x] DuckDB - Provide unifying `etl_` view for ETL build steps. Downstream bronze and silver tables require data from both `live_` and `build_` tables. [#810](https://github.com/oceanprotocol/pdr-backend/issues/810)
- [x] DuckDB - Update ETL "bronze step" to use duckdb/sql [#738](https://github.com/oceanprotocol/pdr-backend/issues/738)
- [x] DuckDB - Clean up any final queries that fetch the whole database system. No select * from table_name anywhere. [#809](https://github.com/oceanprotocol/pdr-backend/issues/809)
- [x] DuckDB - Create logic to support an etl_view that joins both live + temp tables, making it easier to query data as it's being built [#810](https://github.com/oceanprotocol/pdr-backend/issues/810)
- [x] DuckDB - Port latest ETL "bronze slots" to use duckdb/sql [#740](https://github.com/oceanprotocol/pdr-backend/issues/740)
- [x] DuckDB - Extend test coverage to simulate multiple runs, and cover more edge cases. [#811](https://github.com/oceanprotocol/pdr-backend/issues/811)
- [x] DuckDB - Abstract [Prod->Temp->View] pattern [#881](https://github.com/oceanprotocol/pdr-backend/issues/881)
- [x] Accuracy - Update accuracy endpoint to use the ETL to get and store the data. [#854](https://github.com/oceanprotocol/pdr-backend/issues/854)
- [x] Streamlit - Integrate predictoor_income work and dashboards [#612](https://github.com/oceanprotocol/pdr-backend/issues/612)

**[ETL CLI Deliverables]**
- [x] Update ETL CLI and provide a clean interface that helps enforce SLAs. [#703](https://github.com/oceanprotocol/pdr-backend/issues/703)
- [x] Create `pdr analytics describe, query, validate, resume` CLI command [#883](https://github.com/oceanprotocol/pdr-backend/issues/883)

**[Cleanup Deliverables]**
- [x] Cleanup DuckDB implementation, remove hanging dependencies, remove table.df caching, switching from parquet to CSV, cleanup tests. [#737](https://github.com/oceanprotocol/pdr-backend/issues/737)
- [x] Clean truevalue and predvalue [#664](https://github.com/oceanprotocol/pdr-backend/pull/664)
- [x] Improve CSVDataStore and PersistentDataStore instantiation inside Table [#773](https://github.com/oceanprotocol/pdr-backend/issues/773)
- [x] Cleanup Tables, query them directly through CSVDataStore + PersistentDataStore [#772](https://github.com/oceanprotocol/pdr-backend/issues/772)
- [x] Remove reference to `parquet_dir` use `lake_dir` instead [#770](https://github.com/oceanprotocol/pdr-backend/issues/770)
- [x] PDS thread tests are failing, although CI/CD passes. [#941](https://github.com/oceanprotocol/pdr-backend/issues/941)
- [x] OHLCV + CSVDS has been reconciled [#858](https://github.com/oceanprotocol/pdr-backend/pull/858)
- [x] Lake cli command to update is implemented [#953](https://github.com/oceanprotocol/pdr-backend/issues/953)
- [x] Fix issue where CSV data exists, but raw table won't be recreated [#1038](https://github.com/oceanprotocol/pdr-backend/issues/1038)
- [x] Fix pdr-slots and quey logic that's causing the pipeline to break [#1036](https://github.com/oceanprotocol/pdr-backend/issues/1036)
- [x] Time functions are returning local timestamp and breaking the pipeline [#1070](https://github.com/oceanprotocol/pdr-backend/issues/1070)
- [x] Use max(values) to get the max timestamp across all duckdb tables [#1049](https://github.com/oceanprotocol/pdr-backend/issues/1049)
- [x] Expand validation tool to check/report duplicate rows [#1058](https://github.com/oceanprotocol/pdr-backend/issues/1058)
- [x] Update GQLDF to use the same end_ts for all subgraph queries. [#1068](https://github.com/oceanprotocol/pdr-backend/issues/1068) 
- [x] Stabilize Lake Validation & CLI Commands [#1036](https://github.com/oceanprotocol/pdr-backend/issues/1036)
- [x] Fix drop logic to use the proper timetamp, and not drop the whole table [#1079](https://github.com/oceanprotocol/pdr-backend/issues/1079)
- [x] Verify lake behavior is working as expected [#1000](https://github.com/oceanprotocol/pdr-backend/issues/1000)
- [x] DuckDB - Use bronze-predictions for checkpoint [#982](https://github.com/oceanprotocol/pdr-backend/issues/982) 
- [x] Expand ETL coverage to have multiple days of data (1mb files) and multiple operations. Enforce a benchmark performance against this.

**[Ratchet Integration]**
- [x] https://github.com/oceanprotocol/pdr-backend/issues/1109

**[Post-DuckDB Merge - Core Functionality]**
- [ ] Verify incremental table updates are working as expected [#1001](https://github.com/oceanprotocol/pdr-backend/issues/1001)
- [ ] Readme for working the lake and completing UX e2e is documented and works well end-to-end [#1002](https://github.com/oceanprotocol/pdr-backend/issues/1002)
- [ ] DuckDB - Implement "silver predictions" [#665](https://github.com/oceanprotocol/pdr-backend/pull/665)
- [ ] DuckDB - Port latest ETL "silver predictions" to use duckdb/sql + close old PR [#741](https://github.com/oceanprotocol/pdr-backend/issues/741)
- [ ] DuckDB - Silver predictions SQL PR [#848](https://github.com/oceanprotocol/pdr-backend/pull/848)

**[Post-DuckDB - Peripheral Functionality]**
These are frozen. Do not start/complete until DuckDB review/work is complete.
- [x] Update OHCLV Data Factory to use DataStores [#769](https://github.com/oceanprotocol/pdr-backend/issues/769)
- [x] TableRegistry looks redundant now. Deprecate it. [#1088](https://github.com/oceanprotocol/pdr-backend/issues/1088)
- [ ] PredictoorETL is handling st_ts and end_ts correctly [#1086](https://github.com/oceanprotocol/pdr-backend/issues/1086)
- [ ] Re-enable slots and subscription raw tables.
- [ ] DuckDB - Re-enable subscription table [#1085](https://github.com/oceanprotocol/pdr-backend/issues/1085)
- [ ] DuckDB - Re-enable bronze_slots tables - [#595](https://github.com/oceanprotocol/pdr-backend/issues/595)
- [ ] ETL - Cleanup payout, truevals, and revenue calculations - [#1183](https://github.com/oceanprotocol/pdr-backend/issues/1183)
- [ ] Data Store Objects - Please rename functions to use sql nomenclature: `fill` becomes `insert`, `override` becomes `upsert`
- [ ] OHLCV + CSVDS will be updated after DuckDB has been updated [#769](https://github.com/oceanprotocol/pdr-backend/issues/769)
- [ ] If you delete CSVs and rebuild RAW tables, you get duplicate data [#1087](https://github.com/oceanprotocol/pdr-backend/issues/1087)

**Comment by KatunaNorbert** [comment]
Discovered some issues related to data fetching on the main branch, because multiple things are rewritten in the ETF flow I leave them here in case they got solved along the way, if not maybe here would be the place to solve them:

1. Column don't match: "timestamp" and "tx_id" - solved if file is deleted
<img width="1359" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTRvQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--63364da9ee4860d582b3886e4f264d4a92fdb0b1/Screenshot%202024-04-02%20at%2010.05.49.png" alt="Screenshot 2024-04-02 at 10.05.49.png" />


2. Error on saving data - solved if the gql command is rerun
<img width="1703" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkFvQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0367355ff92d5a8e218f7284745e80e01edf6bf8/Screenshot%202024-04-02%20at%2010.12.45.png" alt="Screenshot 2024-04-02 at 10.12.45.png" />

**Comment by idiom-bytes** [comment]
Simply integrate the accuracy code when it's ready to go... until then, i'll be integrating the duckdb PR piece-by-piece.
https://github.com/oceanprotocol/pdr-backend/issues/1102

**Comment by idiom-bytes** [comment]
Closing this ticket and moving remaining items to some other ticket so i can reconcile outstanding issues.
