### ISSUE TITLE
[Sim, make $] Easier benchmarking, via new 'multisim' CLI command

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#779]
### Background / motivation

The challenge: we want to know the effects of various ppss parameters in simulation. 

We want to run sweeps across >1 ppss params, and output key results ($ made, accuracy, other) into a csv table.

Candidate approaches: (a) user does each run manually, (b) user has their own custom setups, (c) put it inside 'sim' CLI command, and (d) new 'mu' CLI command.

We'll use approach (d). Best UX, and effort to build it isn't high.

Q: why 'multisim' and not eg 'simsweep'? 
A: it makes it easier for us to extend the meta-algorithm that's doing sim-in-loop, while retaining the same ppss setup that specifies what parameters to sweep across (and values to test)
- For _this_ issue, it's simply a grid search that outputs to csv. 
- Soon, we will use an optimizer to auto-discover the best-performing combination of params. 
- It also opens up to having "fast sweep" that uses model-building to adaptively sample 

### TODOs / DoD

- [x] First cut: most things end-to-end. Refactoring at cli level.
- [x] multisim_ss properly iterates through combos, via PointMeta as multibit counter
- [x] All end-to-end. Includes: Properly updates PPSS each time; this means maybe getting deeper into dot notation.
- [x] Support different multifeeds
- ~~Optimize: multiprocess~~ --> moved to [#804](https://github.com/oceanprotocol/pdr-backend/issues/804)

**Comment by trentmc** [comment]
Did all but multiprocess in PR https://github.com/oceanprotocol/pdr-backend/pull/783, commit https://github.com/oceanprotocol/pdr-backend/commit/e9795f529140e838dab68b96eaf05924f70f66f0
