### ISSUE TITLE
[Lake][ETL] Extend ETL test coverage to simulate multiple runs.

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-backend#811]
### Background / motivation

As laid out in #810, the pipeline is going to run into issues as it assumes that all data is going to exist in the same step. However, this is not the case and there will be existing data in `live_` table that needs to be processed.

To address this, we should extend test coverage such that it simulates multiple builds and covers this scenario.

**silver-predictions is a great example of this dependency in practice**

### TODOs / DoD
- [x] Update test_etl.py or add new test coverage that executes a multi-stage ETL pipeline
- [x] First run needs to contain data that will be required by the second run
- [x] Second run should depend on data that is already existent on `live_` tables that were yielded as a result of first run
- [x] Test coverage should validate that ETL is able to process data from runs that completed (1st run), in addition to data that was recently generated into `build_` tables as a result of the current run (2nd run).
- [ ] Test coverage should validate that `silver-prediction` table is working as expected
