### ISSUE TITLE
[Sim Engine][Data Layer] Abstract Sim Engine data layer through duck_db

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-backend#817]
### Background / motivation

In order to tech spike a JS-app and test lag/speed of charts, we want to continue to validate it against SimEngine since it has the most complex data-layer so far.

### TODOs / DoD

- [ ] Branch off latest Main + DuckDb Integration such that SimEngine data is yielded into DuckDB SimEngine
- [ ] DuckDB SimEngine schema/tables should be considerate of different "runs" such that we can separate what data we can visualize
- [ ] Latest implementation of SimEngine Streamlit plots consume from DuckDB tables

**Comment by trentmc** [comment]
We're not going to do this
