### ISSUE TITLE
contract.py does way too much, refactor it

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#86]
### Background / motivation

utils/contract.py is pretty large. It has
- network support functions like `send_encrypted_tx()`
- `Web3Config`
- class definition wrappers for: Token, PredictoorContract, FixedRate, ERC721Factory, DataNft

This also means that utils/test_contract.py is extra-large

### TODOs

- [x] Break contract.py into a few modules:
  - networkutil.py
  - web3util.py
  - ../models/token.py (holding Token), ../models/predictoor_contract.py (holding Predictoor), etc
  - contract.py - what's left: address mgmt, abi, etc
- [x] Update test structure accordingly
- [x] Rename utils/ -> util/
- [ ] Tests pass in PR
