### ISSUE TITLE
[Lake][Tables][SQL-Temp-Prod Pattern] Abstract SQL-Temp-Prod pattern and a clean NamedTable object

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-backend#881]
### Background / motivation

As a result of #866, it was recommended to not use a list[name] to store types, and it could perhaps cause troubles. 

The suggestion is to:
```
Create a Table (or NamedTable...?) class which would hold the table name and type. It would support direct access to the attributes and make for better separation of concerns. I don't really agree with having the same table type for a list of table_names, it looks like it could cause troubles in the future and is not flexible for mixed queries.

The NamedTable class would of course hold functionality to get_table_with_name and the initialisation would happen outside this function.

Such a change would greatly improve other parts of the code as well, where such concerns are mixed and prone to bugs.
```
https://github.com/oceanprotocol/pdr-backend/pull/866#discussion_r1560642596

Therefore: `tables[List[NamedTable]]` instead of table_names, get rid of table_type param altogether, then `if table.name not in all_db_tables`

### TODOs / DoD
- [x] Review the [Prod -> Temp -> View -> Prod] pattern such that we can continue to abstract and re-use it
- [x] Update list[name] such that it's more oop/resillient such as using a NamedTable
- [x] Tables, TableTypes, and ETL pattern are further abstracted and crystalized

### Related github issues

- [#866](https://github.com/oceanprotocol/pdr-backend/issues/866)

**Comment by idiom-bytes** [comment]
This has been completed as a result of schema/table improvements
