### ISSUE TITLE
[Lake][CLI] Create lake describe command to output table summary

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-backend#883]
### Background / motivation
It's hard to debug the lake and tables. Let's create a CLI command that facilitates this.

### TODOs / DoD
- [ ] Fix issues w/ lake not populating correctly
- [ ] Create CLI command + functions required to generate a summary of all duckdb tables
- [ ] Log summary to cout

### Related github issues
- [#703](https://github.com/oceanprotocol/pdr-backend/issues/703)
