### ISSUE TITLE
[Aimodel] Add Jaime's techniques: balance class weights in logistic regression, calibrate with isotonic

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#890]
### Background / motivation

Jaime's model is doing well. We want to incorporate it into the main pdr-backend codebase, so that (a) Jaime can iterate faster there (b) we can support Jaime better, and optimize the model further (c) others can benefit from the model.

### TODOs / DoD

Things to change:
- [x] LogisticRegression: max_iter=1000
- [x] CalibratedClassifierCV : give choice of method = `sigmoid` vs `isotonic` (I'd used the former; Jaime the latter)
- [x] LogisticRegression: give choice of class_weight = None vs `balanced` (I'd used the former; Jaime the latter)

For each change, ensure these are updated as needed:
- [`ppss.yaml`](https://github.com/oceanprotocol/pdr-backend/blob/main/ppss.yaml): in `aimodel_ss` - update new setting in corresponding params
- [`ppss/aimodel_ss::AimodelSS`](https://github.com/oceanprotocol/pdr-backend/blob/main/pdr_backend/ppss/aimodel_ss.py): implement as needed
- ppss/test/test_aimodel_ss: add unit test
- [`aimodel/aimodel_data_factory.py::AimodelDataFactory`](https://github.com/oceanprotocol/pdr-backend/blob/main/pdr_backend/aimodel/aimodel_data_factory.py): actual implementation
- aimodel/tests/test_aimodel_factory.py: add unit test

### Appendix: About Jaime's Model

From Jaime:

Here is the repo https://github.com/oceanprotocol/trading-experiment, S04_predictor_models.py has all the logic to train the models for all the feeds, it saves the results in a dictionary where the keys are the feeds names, including parameters such as lags, timeframe and the cross-validation accuracy in the historical data. I trained those models with data starting on 2020 for BTC and 2021 for the rest of coins.

**Comment by trentmc** [comment]
cc @jfdelgad @trizin

**Comment by trentmc** [comment]
> Shouldn't they benefit from the model by purchasing the feed? Jaime's model has been performing well, and if we make it available publicly, people could use it to obtain predictions rather than purchasing the feed. Additionally, diversity in approaches could be beneficial if individuals develop their own solutions/models.

We want "good defaults" for people to use. 
- The better the defaults, the higher the overall accuracy, the more potential $ traders make. 
- And, the better the defaults, the more that predictoors compete by improving on the baseline default
