### ISSUE TITLE
[EPIC, Sim plot] Port streamlit -> Dash

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#906]
### Background / motivation

Coming into this issue, we have already converted matplotlib plots to streamlit.

Now, our goal is: In var importance plot: click on a bar (for a var), and show response vs. var. And, that's a "canary in the mine" for other future interactivity

What: In SimEngine's var importance plot: click on a bar (for a var), and show 1d response vs. var. (We already have the response vs var plot; it shows up when we have just 1 input var)

Bonus: select & click on 2 vars, then it shows 2d response vs var (ie contour plot; which we already have too)

The challenge: input from one streamlit plot interacting with another. There are probably a few ways to do this. It will be useful to explore them, because we will want to repeat the pattern elsewhere. 

Update: from initial experiments, the solution was to port from streamlit to Dash. That's what this github issue ended up being about.

### TODOs

- [x] Explore ways to do it, with mini tech spikes etc
- [x] Choose a way. Do it. (Chosen way: port streamlit -> dash. This issue's description was updated accordingly.)
- [x] in predictoor bot analytics: (ideally) plot sim var importance plot, response surface contours & 1d. This won't be easy, because that data isn't available on chain, so we need to expose it somehow for the analytics tool to see. (With proper privacy: I can only see that info for my predictoor bot, and any other bot that has shared with me.)
- [x] in predictoor bot analytics: in var. importance plot: click on a bar (for a var), and show response vs. var.
