### ISSUE TITLE
[EPIC, Make $] Explore Arbitrum DEXes (GMX, etc): research, add to data_factory & sim, then live tests

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#910]
### Background / motivation

Arbitrum has several promising DEXes for us:

- 4 of the top 5 derivatives DEXes are on arbitrum
- 3 of the top 10 L2 DEXs are on arbitrum

Their top 3 DEXes by volume are:

1. GMX
2. Hyperliquid (synthetic perps)
3. Vertex 

Also, Camelot and Uniswap have high volume. 

### TODOs / DoD

- [ ] Research fees and slippage for each
  - [ ] GMX
  - [ ] Hyperliquid
  - [ ] Vertex
- [ ] Pick most promising from ^ to pursue first
- [ ] Integrate it
  - [ ] Add to fetch_ohlcv, data_factory
  - [ ] Add to sim
- [ ] Run sim benchmarks
- [ ] Run live tests
- [ ] If make $, stop. Else try other exchanges

Final step, if make $ here: add new epic for putting live Predictoor feeds for the exchange

**Comment by trentmc** [comment]
> Berkay: should we close this as well?

Are its fees lower / the same as binance futures?

**Comment by trentmc** [comment]
OK let's close this then.

Cc @calina-c
