### ISSUE TITLE
[PPSS, Aimodel] predictoor_ss.aimodel_ss.input_feeds is redundant with new predictoor_ss.feeds.train_on

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#912]
### TODOs / DoD

- [ ] Deprecate `predictoor_ss.aimodel_ss.input_feeds`:
  - [x] Remove from `ppss.yaml`
  - [x] Remove from `aimodel_ss.py` & `test_aimodel_ss.py`
  - [x] Update anything that depended on `predictoor_ss.aimodel_ss.input_feeds` 
  - [x] Update `test_aimodel_data_factory.py`
  - [x] Rename `PredictFeed`, `PredictFeeds`, to `PredictTrainFeedset`, `PredictTrainFeedsets`
  - [x] Split `predict_feeds.py` into `predict_train_feedset.py`, `predict_train_feedsets.py`, `parse_feed_obj.py`. Ensure 3 separate test files too.
  - [ ] Ensure that all d["predict_feed"] is actually d["feeds"]
  - [ ] Remove `aimodel_ss.input_feeds` from `ppss.py` & `test_ppss.py`
  - [ ] Update anything that depended on anything that `predictoor_ss.aimodel_ss` inherited from `ppss/base_ss.py::MultiFeedMixin`
  - [ ] Update anything that depended on `predictoor_ss.aimodel_ss.n` (because that property depended on 
  - [ ] Update other tests as needed
- [ ] Test from cli, in `pdr sim` and `pdr predictoor` 

Context below.

### Background / motivation

Issue [#701](https://github.com/oceanprotocol/pdr-backend/issues/701) is "[Epic][Pdr bot] New smart contract, so user needs just one tx for 2-sided predictions across >1 feeds". It was merged Apr 16 in commit https://github.com/oceanprotocol/pdr-backend/commit/96c0da83ab9df98b3f2262f17cf7e2c477dc21b6.

It updated PPSS `predictoor_ss` feeds structure, to allow >1 feeds to predict on; and for each feed a compact way to specify what input feeds the model should use. Example:
```yaml
predictoor_ss:
  feeds: 
    - predict: binance BTC/USDT ETH/USDT c 5m
      train_on:
      - binance BTC/USDT ETH/USDT c 5m
      - kraken BTC/USDT c 5m
    - predict: binance BTC/USDT ETH/USDT c 1h
      train_on:
      - binance BTC/USDT ETH/USDT c 1h
```

The structure for PPSS `predictoor_ss.aimodel_ss` was not changed. It retains its way to specify input_feeds. Example:
```yaml
predictoor_ss:
...
  aimodel_ss:
    input_feeds:
      - binance BTC/USDT ETH/USDT c 5m
...
```

The problem is with specifying model input feeds. Specifically `predictoor_ss.aimodel_ss.input_feeds` is redundant with new `predictoor_ss.feeds.train_on`.

What to do? 
- Option 1: specify input feeds only within `predictoor_ss.aimodel_ss.input_feeds` [old way]
- Option 2: specify input feeds only within `predictoor_ss.feeds.train_on` [new way]

Option 2 assumes that AimodelFactory can see all of PredictoorSS. (This is the only way that Option 2 can work.)

Option 2 is keeps the prediction feed next to the input feeds. This was the intent during the design of #701. This makes it cleaner than option 1. Therefore, option 2 is preferable over option 1. 

Option 1 doesn't currently have a means to link prediction feed with train feeds. And building one would mean more redundancy. So option 1 is actually a no-go.

But there is a small challenge in option 2. We'd like model-building to be independent of having to know all of predictoor_ss. Yet the input feeds are specified at a level higher than aimodel_ss. Idea:
- Option 3: 
  - For end-to-end runs: PPSS has `predictoor_ss.feeds.train_on` [new way] feeds values, and `predictoor_ss.aimodel_ss.input_feeds` value of `UsePredictoorSsFeeds`. Then when model-building, it JIT fills in `predictoor_ss.aimodel_ss.input_feeds` to relevant feeds values.
  - Therefore `AimodelFactory` expects `predictoor_ss.aimodel_ss.input_feeds` to have proper feed values, like in status quo. Therefore its tests remain like now

Option 3 is more complex than option 2. 

Let's revisit the motivation for option 3: "we'd like model-building to be independent of having to know all of predictoor_ss." There are actually two parts of model-building strategy:
- (a) which input feeds -> this is outside of AimodelFactory. Because AimodelFactory takes in an X, y 
- (b) specific things for AimodelFactory: what modeling technique, etc
- It's actually ok for AimodelFactory / its SS to _not_ know (a). In fact that's probably preferable! Because it really only needs (b) anyway. Therefore the motivation for option 3 goes away.

Therefore option 2 is the best choice.

### Appendix: on renaming from PredictFeed

```python
class PredictFeed:
    Easy manipulation of a single (predict feed / train_on feeds).

    To be precise, it has:
    - 1 feed to predict
    - >=1 feeds as inputs to the model

    Therefore 'PredictFeed' is a misnomer, since it isn't just one feed. 
    TODO: rename PredictFeed, PredictFeeds, predict_feeds.py
    Candidate names:
      PredictTrainFeedset, #chosen
      PredictTrainFeedSet,
      PredictTrainFeedGroup,
      PredictTrainFeedset,
      PredictoorTrainFeedset,
      PredictoorFeedSet,
      PredictoorFeedset,
```
