### ISSUE TITLE
[Sim engine, UX] Poor indication that sim engine has started

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#937]
### Background / motivation

As of a few days ago, if I ran `pdr sim`, then it would start giving me logging output within a couple seconds of starting. (Assuming `sim_engine` log level is `INFO`.) That's great, I know that it's working.

But now when I go to run it, it's about 30 seconds before I see any logs. As a symptom, I found myself hitting ctrl-c a couple times because I was worried it was in an infinite loop. (It wasn't). 

### Towards a solution

Here's the code.

```python
    @enforce_types
    def _init_loop_attributes(self):
        filebase = f"out_{UnixTimeMs.now()}.txt"
        self.logfile = os.path.join(self.ppss.sim_ss.log_dir, filebase)

        fh = logging.FileHandler(self.logfile)
        fh.setLevel(logging.INFO)
        logger.addHandler(fh)

        self.st.init_loop_attributes()

    @enforce_types
    def run(self):
        self._init_loop_attributes()
        logger.info("Start run")

        self.sim_plotter.init_state(self.multi_id)

        # main loop!
        f = OhlcvDataFactory(self.ppss.lake_ss)
        mergedohlcv_df = f.get_mergedohlcv_df()
        for test_i in range(self.ppss.sim_ss.test_n):
            self.run_one_iter(test_i, mergedohlcv_df)

        logger.info("Done all iters.")
```

The main routine is `run()`. See how it calls `_init_loop_attributes()` before it does its first log `"Start run"`. That's the main culprit.

Part of the culprit: I see that the line `self.sim_plotter.init_state(self.multi_id)` is in `run()`. It really should be in the last line of `_init_loop_attributes()`, which is where everything is supposed to be initialized. 
- I believe `sim_plotter.init_state()` is slow

### TODOs / DoD

- [ ] Move `self.sim_plotter.init_state(self.multi_id)` to the last line of `_init_loop_attributes()`.
- [ ] Move `logger.info("Start run")` so that it's at the very top of `run()`.
- [ ] Add a line `logger.info("Initialize plots") right above the call to `sim_plotter.init_state()`

Then it should all be fine!

**Comment by calina-c** [comment]
@trentmc I already started converting the Streamlit dashboard into a Dash one, so most of these are moot. Dash has a different refreshing mechanism so most of the `while True` stuff I've been doing with Streamlit will disappear.

I am keeping this issue open to comb through it once done, and make sure everything is covered.
