### ISSUE TITLE
[YAML]  pred_submitter_mgr should be in predictoor_ss.bot_only, not predictoor_ss

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#942]
### Background / motivation

Here's part of `ppss.yaml` in `predictoor_ss`:
```pytest
predictoor_ss:
  predict_train_feedsets: 
     ...
  approach: 2 ...
  stake_amount: 1 ...
  pred_submitter_mgr: "DeployNewMgr" # DeployNewMgr | <address of deployed mgr>  
  sim_only: ...
    ...

  bot_only:
    s_start_payouts: 220 # in s. Run payout if > this time left. 0 to disable
    s_until_epoch_end: 60 # in s. Start predicting if > this time left

  aimodel_ss:
    max_n_train: 20000 # no. epochs to train model on
```

The `sim_only` section is for settings only relevant for simulation. The `bot_only` section is for settings only relevant to running the bot with smart contracts. (Settings that are relevant to both are in the higher level. Unless they're for `aimodel` which is below the other two.)

See how `pred_submitter_mgr` is in the highest layer of `predictoor_ss`. Yet `pred_submitter_mgr` is a setting that's only relevant to `bot_only`. **This is the problem.**

### TODOs

- [ ] In `ppss.yaml`, move `pred_submitter_mgr` into `predictoor_ss.bot_only` section
- [ ] Update predictoor_ss.py, test_predictoor_ss.py as needed
- [ ] Update other code as needed
