### ISSUE TITLE
[Sim plots] Write blog post  about new sim analytics with dash

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#960]
### Background / motivation

Previously: simulator analytics plots were with matplotlib. 
- Benefits: (a) we get plots! Way more insight. (b) Plots were created in python, so we could rapidly improve them. We & our users are all data scientists operating in py
- But there were issues: (a) takes up whole screen and keeps popping up (b) once they're done they're done, can't retrieve later (c) matplotlib interactivity options are severely limited (d) local only

New: simulator analytics plots that show up in browser, via Dash
- Benefits: like before. Plus: overcomes all the issues of before!

Goal: write a blog post & video about this. 
- Q: We could do it (i) just for simulator, or (ii) sim _and_ predictoor bot analytics. Which to do? 
- A: [Trent] For _this_ issue to do just (i). Then do predictoor bot analytics in a follow-up post / video.
- Q: The product actually evolved from matplotlib -> streamlit -> Dash. We just never announced streamlit before. How to handle?
- A: focus on the jump from matplotlib -> dash. Simply mention that we tried streamlit along the way, but its options for interactivity were limited compared to Dash. 

### TODOs / DoD

Blog post:
- [x] [V] Write draft blog post that (a) describes the before-and-after above (b) does a walk-through of what there is now
- [x] [Trent] Review & edit post
- [x] Publish blog post. [Here](https://blog.oceanprotocol.com/predictoor-simulator-analytics-are-now-webapp-based-and-persistent-4ddabcb9cfb1). 
- [x] Tweet about blog post. [Here](https://x.com/predictoor_ai/status/1793331258153435430)

### Related github issues

- Matpotlib -> streamlit: [#479](https://github.com/oceanprotocol/pdr-backend/issues/749)
- Streamlit -> Dash: [#906](https://github.com/oceanprotocol/pdr-backend/issues/906)

**Comment by trentmc** [comment]
Not doing video now, so can close
