### ISSUE TITLE
[UX] Write blog post about how predictoor dynamics have shifted to 'maximize accuracy'

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#961]
### Background / motivation

Epic [#680](https://github.com/oceanprotocol/pdr-backend/issues/680) was for "two-sided prediction bots", with sub-issues for implementation and a blog post [#679](https://github.com/oceanprotocol/pdr-backend/issues/679).

The resulting blog post does a nice job explaining the 50-50 problem, and what was built to fix it. [Link](https://blog.oceanprotocol.com/predictoor-introducing-two-sided-prediction-bots-66bbbb53be1b). And a good [tweetstorm](https://twitter.com/predictoor_ai/status/1762709586946011483) accompanied it.

So we had a _theory_ on how to stop 50-50 dynamics. And built it. That was above.

From the last few weeks, we have new data showing that it's working! The game has shifted from "50-50 with high stakes" to "maximize accuracy"
- predictoor.ai accuracies have clearly jumped
- stake has decreased as the 50-50 game (with high stake) is no longer profitable
- and most usefully, @trizin has created plots showing how accuracy itself has increased in the previous few weeks

Goal of this issue: write a blog post showing this. Cover the points from above. That is:
- a summary of content from the previous blog post as a backgrounder (with a link to the blog post & tweetstorm)
- new data showing that what we built is working

### TODOs / DoD

- [x] [Berkay, with Jaime] Write blog post. [Draft](https://docs.google.com/document/d/19KqYYeedzUEnj1S-tDQ_C30uZr2vSQpYsHpauLkiXQU/edit#heading=h.gfzx1886lx01)
- [x] Get reviews from Roberto & Trent
- [x] [T] Revise post, put on medium
- [x] [T] Publish blog post [link](https://blog.oceanprotocol.com/predictoor-dynamics-have-shifted-towards-accuracy-b4a537b930d2)
- [x] [T] Publish tweetstorm [link](https://twitter.com/predictoor_ai/status/1787458915468206250)

**Comment by trentmc** [comment]
All done!
