### ISSUE TITLE
[CLI, sim plots] 'pdr sim_plots' should be the way to start simulation plots, not 'sim_plots'

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-backend#968]
### Background / motivation

The new Dash plot framework is now in main, via commit https://github.com/oceanprotocol/pdr-backend/commit/c0f2470c7e577181421b75666b692819d29a0943). [PR #938](https://github.com/oceanprotocol/pdr-backend/pull/938). Great! :)

The console-level instructions to make it go are:

```console
sim_plots
```

The problem: this is inconsistent with the rest of the Predictoor CLI. 

What it should be:
```console
pdr sim_plots
```

Furthermore, `sim_plots` Python module is now in the root directory, and from what I can tell, it doesn't need to be.

### TODOs

- [ ] Change things so that I start plots via `pdr sim_plots`
  - [ ] Where the implementation uses `cli/` rather than directly in the root directory to handle the CLI side. 
  - [ ] And remaining code of `sim_plots` should be in `sim/` directory
- [ ] update `predictoor.md` and `trader.md` READMEs accordingly
