### ISSUE TITLE
[Lake][Subgraph] Clean up subgraph objects, use pydantic table objects instead.

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-backend#974]
### Background / motivation
Subgraph objects (Prediction, Slot, Payout, Subscription) are unnecessary and redundant.

Subgraph fetching is part of data-integration, the flow should be:
1. to validate it
2. save it to CSV
3. add to duckdb-lake

Perhaps, make sure that pydantic update is in place - #973

### TODOs / DoD
- [ ] Remove redundant data objects inside subgraph
- [ ] Utilize pydantic objects for validating data coming from subgraph
- [ ] Update tests or anywhere else as required

**Comment by calina-c** [comment]
@idiom-bytes I think this can be closed, right?

**Comment by idiom-bytes** [comment]
Yes it can, closing...
