### ISSUE TITLE
[Lake][Incremental Pipeline] Use bronze_pdr_predictions to manage active checkpoint

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-backend#982]
### Background / motivation

Inferring where to resume the pipeline from is having issues.

It's not about "removing subscriptions" from this logic, we need to think about the system and what it's trying t do.

Rather than querying all tables to find the timestamp from where to resume the pipeline, just use the following for now:
- raw_predictions for GQLDF
- bronze_pdr_predictions for ETL

### Macro

let's break down what's happening here

**we're querying the data tables from duckdb, in order to understand how to resume the jobs pipeline incrementally**

basically, resuming from where it left off

i had mentioned in the past updating my_ppss.yaml such that st_ts is mutated w/ the last_run_timestamp and the pipeline enforces being incremental rather than trying to do it through data-inference (like ohlcv data factory)... but, this kind of breaks the pattern for how the yaml file is being used.

it also doesn't provide a way to track the etl/workflow runs, such that they can be rolledback in a systemic way

so, let's do this:
- [x] document this (so it's clear how this is expected to work) and how we plan to solve it properly
1. use raw_predictions/bronze_predictions max_timestamps to resume GQLDF/ETL.
1. ship duckdb integration
1. start tracking the runs in duckdb, and using these as the checkpoint for how to run the next GQLDF/ETL run

### TODOs / DoD

**Checkpoints & Incremental Pipeline**
============
Update GQLDF and ETL logic, to resume from their equivalent prediction tables.

**To run GQLDF**
- We're going to use the st_ts from the last(raw_pdr_predictions) in duck_db
- We're going to use the end_ts from ppss.lake_ss.end_ts = now

**To run ETL**
- We're going to use the st_ts from the last(raw_pdr_predictions) in duck_db
- We're going to use the end_ts from the last(temp_raw_pdr_predictions) in duck_db (it could also be ppss.lake_ss.end_ts = now)

This will KISS and let us ship a simple incremental pipeline that works reliably and gives us the data quality we need.
We'll worry about implementing a job object to abstract this later.

This means your ppss can be:
st_ts: 01-01-2024
end_ts: now

...and it should just work

Tasks:
- [x] Update GQLDF to start/end from the correct spot
- [x] Update ETL to start/end from the correct spot

**Comment by kdetry** [comment]
The problem we are facing is not related to the start time of the ETL process. Therefore, updating the ETL logic and running the process from the last timestamp of the bronze_predictions table is not a viable solution.

The actual issue is that the fin_ms value on the bronze_prediction (or bronze_slots) table is incorrect and is taken from the pdr_subscriptions table.

**Comment by KatunaNorbert** [comment]
Since we are not doing any kind of updates on the bronze tables, just inserting into the table, I think the logic should be the following:
`fin_ms` should be `fin_timestr` from ppss.yaml which then should be same as the raw tables value

**Comment by kdetry** [comment]
If we set the value to be the same as the one in the ppss.yaml file and the value is set to "now", some truevals and payouts may not be ready yet. Therefore, we need to use the same logic but calculate only the necessary tables for each bronze table.

**Comment by KatunaNorbert** [comment]
If truevals or payours or other values are not ready then we should do updates when the values are ready. Right now the silver step is only doing inserts and I don't think we should be holding back on values if data is missing. We should have same rows as raw tables and do updates whenever missing data becomes available

**Comment by kdetry** [comment]
Updating means also checking the data (row by row) and we have to take the data from DB and convert to polars again. That is what we avoid from

**Comment by idiom-bytes** [comment]
Basic implementation of Raw + ETL checkpoints is now working.
https://github.com/oceanprotocol/pdr-backend/pull/1077

**Comment by idiom-bytes** [comment]
This has been implemented and completed.
