### ISSUE TITLE
[Lake][Fetching vs Joining] Fetch available data from subgraph rather than joining w/ sql.

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-backend#989]
### Background / motivation

1. It's easier to just fetch the data already from subgraph rather than perform a join (more costly too).
These, shouldn't have to be obtain through a join with the predictions table.
{etl_bronze_pdr_predictions_table_name}.pair as pair,
{etl_bronze_pdr_predictions_table_name}.timeframe as timeframe,
{etl_bronze_pdr_predictions_table_name}.source as source,

2. The issue here too, is that in SQL there is 1 slot event being joined <= N prediction events. Again, costly. This is being done as a left join, but it would be good to check the results of `bronze_pdr_slots.py` as a way to verify this.
![image](https://github.com/oceanprotocol/pdr-backend/assets/69865342/a382b9c8-769b-4f1d-8028-07edfc7fa85d)

### TODOs / DoD
1. Review this query and it's current results/accuracy.
2. Simplify this query by just getting this data from subgraph.
4. Review other subgraph queries & etl joins where this could be simplified and fix them

### Tasks
- [ ] update slots and other tables to get pair/timeframe/source info from subgraph
- [ ] deprecate implementing this in SQL joins
- [ ] verify that queries are generating corect/expected data

**Comment by idiom-bytes** [comment]
Because it feels like the previous work wasn't quite complete.
We can get the data from subgraph and clean this up.

I tagged it as low priority.

**Comment by idiom-bytes** [comment]
I am now reviewing this in issue #1000 and it's coming up again.

The `bronze_slots` query is taking a very long time to complete, and although it may be to other reasons, I can't help but stare at this super expensive join that we can basically get for free.

![Screenshot from 2024-05-14 13-34-33](https://github.com/oceanprotocol/pdr-backend/assets/69865342/800bf2d0-4a36-4063-a75f-a0bf93868520)

**Comment by idiom-bytes** [comment]
This is now being tracked in [#1299](https://github.com/oceanprotocol/pdr-backend/issues/1299) and this will be closed. Please reopen as we address backlog.
